### ISSUE TITLE
new Cookies() in testing environment

### ISSUE THREAD

**Issue by Ancinek** [reactivestack/cookies#100]
I was trying to test my login _flow_ in which I set cookies. I passed them to my `redux-thunk` as an extra argument and then the action calls them like `cookies.set(...)`. It was not working, saying that `TypeError: Cannot set property 'cookie' of undefined`. I checked the package itself and all the stuff was pointing to this line of code (line 80 of Cookies.js)

`document.cookie = _cookie2.default.serialize(name, value, options);`

I'm using `jest` and the `document` object was fully accessible inside my test javascript file, but it was `undefined` inside the package file.

Any idea why does this happen? I switched to `js-cookie` inside my tests and it works perfectly fine.

Link to the SO thread, where I described that issue with a bit more code: [click](https://stackoverflow.com/questions/45944843/document-object-not-accessible-in-package-while-testing)

**Edit**
Seems like `js-cookie` is also not getting the `document` object. They just have a `return` statement if the `document` is `undefined`. Still going to leave it here as I didn't find any information about how to do it properly?

**Comment by eXon** [comment]
This should be fixed in v2.1.0. The library is now 100% compatible with Jest or any testing environment because it no longer rely on Node.js detection. You should be able to use it within your test with the expected result.

**Comment by Ancinek** [comment]
@eXon That's great. Thanks!
