### ISSUE TITLE
Possible non-backwards compatible remove API? ERROR: hooks of undefined

### ISSUE THREAD

**Issue by oshalygin** [reactivestack/cookies#103]
I upgraded from `2.0.8` to `2.1.0` and started throwing errors when removing cookies.

I'm not 100% certain whats going on but what I can tell, in `2.1.0` theres a new prop when calling `new Cookies()` on it which is `hooks`.  Interestingly, that prop has the value of `undefined`.

This code no longer works in `2.1.0`

```javascript

export function removeToken() {
  return new Promise((resolve, reject) => {
    try {
      const cookies = getCookies();
      const allCookies = cookies.getAll();

      Object.keys(allCookies).map(cookies.remove);
      resolve();
    } catch (error) {
      reject(error);
    }
  });
}
```

the caught error is something about `cannot read hooks of undefined`.

I looked at the source code but I'm a bit lost.  Willing to help if someone can guide me where to look.

**Comment by eXon** [comment]
Hi @oshalygin 

It seems strange to me that it was working with the old version. Try to add the `this` reference to your `.map` like so and you should be fine:

```js
export function removeToken() {
  return new Promise((resolve, reject) => {
    try {
      const cookies = getCookies();
      const allCookies = cookies.getAll();

      Object.keys(allCookies).map(cookies.remove, cookies);
      resolve();
    } catch (error) {
      reject(error);
    }
  });
}
```

Let me know if it works!

**Comment by oshalygin** [comment]
@eXon Thanks I'll try that, that actually makes sense when I was analyzing the object and its prototype.

**Comment by eXon** [comment]
I'm guessing this is resolved. Let me know if it's not!

**Comment by oshalygin** [comment]
I actually have been super swamped at work and havent checked, thanks @eXon for following up.  I'll test and comment back here for sure :)

If it still exists I"ll reopen another issue and link it.
