### ISSUE TITLE
Multiple cookes with same key but different domain

### ISSUE THREAD

**Issue by jiangweiliu-aa** [reactivestack/cookies#105]
Here is my code:
```
const cookies = new Cookies(req.headers.cookie);
const lang = cookies.get('lang');
```
document.cookie:
> `lang=cn;lang=jp;`

domain of the first `lang` is `.a.com` and second is `www.a.com`.
`cookies.get` always return me the first cookie instead of the second one, which is my expect value.

I'm hoping that if there is any solution for it. Thanks in advance!

**Comment by eXon** [comment]
Hi @jiangweiliu-aa 

Thank you for sending a bug issue. Unfortunally I haven't found anything in the official cookie specs that talk about cookies on different `domain` and how they should be sorted. However, they will be sorted first with the longer `path`.  This is why only the first cookie value is kept.

This library is using the `[cookie](https://www.npmjs.com/package/cookie)` library. Maybe they know more about this.

```
2.  The user agent SHOULD sort the cookie-list in the following
       order:

       *  Cookies with longer paths are listed before cookies with
          shorter paths.

       *  Among cookies that have equal-length path fields, cookies with
          earlier creation-times are listed before cookies with later
          creation-times.

       NOTE: Not all user agents sort the cookie-list in this order, but
       this order reflects common practice when this document was
       written, and, historically, there have been servers that
       (erroneously) depended on this order.
```

**Comment by jiangweiliu-aa** [comment]
@eXon 

Thanks for your kindly reply and Sorry about that I just saw your message. 
I will check the link you mentioned above.
