### ISSUE TITLE
Reactivestack typings

### ISSUE THREAD

**Issue by inunotaisho26** [reactivestack/cookies#107]
I would like to make a request for react-cookie to have typescript type definitions added. I want to use react-cookie in a project, but I need typings because I write all my React apps in tsx. Makes error catching much smoother.

**Comment by eXon** [comment]
I would be happy to include the TypeScript defintions with the library if somebody can make a PR. I don't have much time for this unfortunally and I'm only fluent with FlowType.

**Comment by PeterKottas** [comment]
Hi gents, I know as I am writing this that I won't be able to do this properly with a PR and possible fixes afterwards. However, I still think somebody might find these useful and they can even end up being official eventually. These are react-cookie typescript typings done in a hurry. I'll update it here if I make any fixes. 

    declare module 'react-cookie' {
        import * as React from 'react';

        export type Cookie = string;

        export class CookiesProvider extends React.Component<{},{}>{}

        export function withCookies<T extends ReactCookieProps>(Component:React.ComponentClass<T>): React.ComponentClass;

        export interface ReactCookieGetOptions{
            doNotParse?: boolean;
        }

        export interface ReactCookieGetAllOptions{
            doNotParse?: boolean;
        }

        export interface ReactCookieSetOptions{
            path?: string;
            expires?: Date;
            maxAge?: number;
            domain?: string;
            secure?: boolean;
            httpOnly?: boolean;
        }

        export interface ReactCookieRemoveOptions{
            path?: string;
            expires?: Date;
            maxAge?: number;
            domain?: string;
            secure?: boolean;
            httpOnly?: boolean;
        }

        export type ReactCookieProps = {
            cookies: {
                get: (key: string, options?: ReactCookieGetOptions) => Cookie;
                getAll: (options?: ReactCookieGetAllOptions) => Cookie[];
                set(name: string, value: string, options?:ReactCookieSetOptions);
                remove(name: string, options?:ReactCookieRemoveOptions);
            }
        };
    }

**Comment by Guymestef** [comment]
Missing class:

    export class Cookies {
        get: (key: string, options?: ReactCookieGetOptions) => Cookie;
        getAll: (options?: ReactCookieGetAllOptions) => Cookie[];
        set(name: string, value: string, options?: ReactCookieSetOptions): void;
        remove(name: string, options?: ReactCookieRemoveOptions): void;
    }

**Comment by PeterKottas** [comment]
That's basically copy paste from what comes into props, isn't it? Would be better to share that among the 2 then. But yep that's right, I admit I only did the ones I use :)

**Comment by Guymestef** [comment]
Yes :)

**Comment by inunotaisho26** [comment]
@eXon Would you be so kind as to update the npm package for react-cookies so the typings are included? I would be willing to work on typings for the remainder of the "cookies" packages.

**Comment by inunotaisho26** [comment]
@eXon The the packagejson was right, but typings were not in latest npm release.

**Comment by orionstudt** [comment]
@Guymestef The `Cookies` typing seems to prevent you from constructing an instance of `Cookies` with `new Cookies([string])`
