### ISSUE TITLE
react-cookie deps should avoid ^ for packages that don't respect semver

### ISSUE THREAD

**Issue by meeech** [reactivestack/cookies#109]
Hi

Using react-cookie 2.0.7 in a project. It relies on universal-cookie ^2.0.1 - which means that for 2.0.7 being installed today pulls 2.1.0, which has breaking changes - so that react-cookie 2.0.7 does not work with 2.1.0. 2.1.0 implies (to me at least) new functionality, but backwards compat.

This issue exists in the current project as well (2.1.1 still relies on ^2.1.0 of universal)

**Comment by eXon** [comment]
semver should be respected, I'm the author of both library. If you see a breaking change please report it!

**Comment by meeech** [comment]
@eXon Sure. What project would you like the report in? The report is as stated in my ticket - 2.0.7 pulls 2.1.0 which had breaking change
