### ISSUE TITLE
Using in jest tests

### ISSUE THREAD

**Issue by taviroquai** [reactivestack/cookies#113]
Hi,

I would like to know out to use it in jest environment once I'm getting this error:

> Cannot read property 'cookie' of undefined
>    at Cookies._updateBrowserValues (/home/bla/app/node_modules/universal-cookie/lib/Cookies.js:47:55)

I tried to set the cookie in the test like this, before calling the usage in app, but it didn't work:
```
import Cookies from 'universal-cookie'
const cookieHandler = new Cookies()
cookieHandler.set('foo', {}, { path: '/' });
```

Thanks

**Comment by charlespeters** [comment]
running into the same thing with cannot read `get` of undefined.
i wonder if we can just mock that out.

**Comment by eXon** [comment]
It should be easy to use `universal-cookie` with unit test. Just make sure you are defining the cookies, you don't need to mock it. All you need is pass an object to `Cookies` just like that:

```js
import Cookies from 'universal-cookie'
const cookieHandler = new Cookies({ myCookie: 'meow!' });
cookieHandler.set('foo', {}, { path: '/' });
```

If you don't have any cookie, you can set an empty object.

**Comment by sylvainpina** [comment]
i have the same issue.
for fix this with jest 22.4.4 i to that, it's creepy but it's work.
```javascript
cookies = new Cookies({})
cookies.HAS_DOCUMENT_COOKIE = false
```
if not, universal-cookie believe environnement is browser, because jest load jsdom...

**Comment by pdesantis** [comment]
I had the same issue, and `cookies.HAS_DOCUMENT_COOKIE = false` fixed it. Thanks @sylvainpina!

Any thoughts on exposing this publicly? Or are there any better ways to make this jest-friendly?

**Comment by chj-damon** [comment]
@eXon I defined the cookie in the test files, but how do I use it in my function?

**Comment by chj-damon** [comment]
@sylvainpina where did you set `cookies.HAS_DOCUMENT_COOKIE = false`? I set cookies in one function and I want to use the cookie in other functions in other files. How can I do that?

**Comment by chj-damon** [comment]
@pdesantis it won't work in typescript.

**Comment by eXon** [comment]
In `v4.0.1`, it should detect JSDOM and skip the browser.

**Comment by mocantimoteidavid** [comment]
Would there be any other solution in making this work in typescript too?

**Comment by kevin-brotcke** [comment]
I was able to fix this in my case by specifying `node` as the jest environment since the code I was testing only runs on the server.

https://jestjs.io/docs/en/configuration.html#testenvironment-string

**Comment by jappareti** [comment]
@chj-damon @mocantimoteidavid I got it to work in typescript by doing this:

```ts
cookies = new Cookies({})
cookies['HAS_DOCUMENT_COOKIE'] = false
```
