### ISSUE TITLE
Removing cookie in browser does not update the Cookies object

### ISSUE THREAD

**Issue by Exomnius** [reactivestack/cookies#115]
When I remove the cookie in my browser, it is still available in memory.
Is there a reason for not removing the cookies in Cookies.js on line 27-29? If not, I could submit a PR to add this functionality.

**Comment by guoyaojie** [comment]
i find the same problem，have u fix it?

**Comment by Exomnius** [comment]
@eXon Can I submit a PR for this? Or what is your opinion?

**Comment by Exomnius** [comment]
#120

**Comment by remhume** [comment]
see #110 (and PR #112)

**Comment by eXon** [comment]
This is fixed in universal-cookie `2.1.1`
