### ISSUE TITLE
How to use cookie in higher order component ?

### ISSUE THREAD

**Issue by bhavin00** [reactivestack/cookies#116]
How to use cookie in higher order component ?

Or in any other xyz.js file which have no react component then how to use the cookie in that file 
?

**Comment by eXon** [comment]
`withCookies` is already a HOC that will give you `cookies` in your props. Then, you can read the value using `this.props.cookies.get('value')` and pass it where you need it or give to your function `this.props.cookies` and get/set cookies latter.
