### ISSUE TITLE
I cant remove cookie

### ISSUE THREAD

**Issue by guoyaojie** [reactivestack/cookies#119]
use API remove method u give us is  completely ineffective；in Cookies.js remove function i find when u delete this.cookie[name] ,this.cookie is change but after execute document.cookie = _cookie2.default.serialize(name, '', finalOptions); document.cookie is still there,how can i fix it ?

![image](https://user-images.githubusercontent.com/17962715/32364040-88845406-c0ad-11e7-8d01-af64e07c43d9.png)
![image](https://user-images.githubusercontent.com/17962715/32364051-9aa2151a-c0ad-11e7-8a49-b6ac3bbe56d6.png)

**Comment by remhume** [comment]
see #110 (and PR #112)

**Comment by eXon** [comment]
This should be fixed in `2.1.1`. Thanks for reporting!
