### ISSUE TITLE
Build is failing on Travis

### ISSUE THREAD

**Issue by oredi** [reactivestack/cookies#121]
Hey @eXon, thanks for the great work on this. 

But it appears that the latest build is failing on SauceLabs, it apparently started on the iPhone tests
06 11 2017 15:57:18.728:ERROR [launcher.sauce]: Can not start iphone 8.2 (OS X 10.10)

**Comment by remhume** [comment]
Yes, the errors say that the account has no permission to start the sauce tests (```{"message": "Not authorized"}```).
Likely the repo owner has not renewed their plan at saucelabs and this why (all of) the saucelabs tests are failing.

**Comment by eXon** [comment]
Open source projects are free with saucelabs so the plan should not be an issue. I'll take a look, this is anoying I agree.

**Comment by eXon** [comment]
It looks like opera was causing some troubles. I experienced some problems with iPhone as well, but that bug was random (re-running the same build would work if it failed).

Now it works :)
