### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by MatthewScholefield** [reactivestack/cookies#127]
Some questions the README left me with:
 - How do I use it / where are docs? Guess: [Universal Cookie Repo](https://github.com/reactivestack/cookies/tree/master/packages/universal-cookie)
 - What's the difference between react-cookies and universal-cookies? Guess: react-native leverages react for speeding something up internally
 - Do you need to install both react-cookies and universal-cookies? Guess: no

Disclaimer: I'm very new to the web development. Perhaps the last two questions are common knowledge.

**Comment by nitins1** [comment]
I'm also very new to web development and I too think this documentation could be improved. 

Could the 'Simple example' be simpler? Could there be comments explaining code that beginners are not likely to understand? 

<Cookies Provider> and withCookies(Component) are still unclear to me, and I'm not sure what they are doing.

I've tried to use snippets of the example in my own code but am not understanding how each snippet works with each other and what each part is doing. Some clarification could help a lot!

**Comment by MatthewScholefield** [comment]
By the way, so far I just ignored this repo, and everything worked fine doing:

```bash
npm install --save universal-cookie
```
```jsx
import Cookies from 'universal-cookie';

const cookies = new Cookies();
let name = cookies.get('name');  # either string or undefined
if (!name) {
    name = "John";
    cookies.set('name', name, {path: '/'});
}
```

**Comment by nitins1** [comment]
How might I use this with react? The react-cookie documentation is can't follow.

Where would I declare the new instance of Cookies? In the constructor? Could I use this format with react?

**Comment by MatthewScholefield** [comment]
@nitins1 Not sure the proper place, but it works to put it in either the constructor or module.

**Comment by eXon** [comment]
You should read the readme on the packages or NPM instead of the GitHub mono repo. The whole documentation is there with examples.
