### ISSUE TITLE
Can't access cookies using this library a;though I am able to do it through document.cookie

### ISSUE THREAD

**Issue by shweta-code** [reactivestack/cookies#129]
Can't access cookies using this library.
Although I am able to do it through document.cookie.
I have ui rendered from localhost:80 although my node is running on localhost:3001.
You can say i have some sort of wrapper on node that serves js files from node.
There are cookies saved in localhost domain . I can see in browser and am able to log them using
document.cookie.
But I am not able  to log cookies using this.props  . Given I have followed your example

**Comment by eXon** [comment]
Would you mind sharing an example? I'm not sure what you are trying to do that fails.
