### ISSUE TITLE
Reading one cookie and setting another for same cookie with different domain.

### ISSUE THREAD

**Issue by shweta-code** [reactivestack/cookies#130]
My host is automation.x.com. I have a cookie with domain .automation.x.com already set in browser with key "preference".
I set the domain artificially for this cookie by prepending a " . " . I set this cookie through backend. Now on client side, when I try to get cookie "preference", it gives me the value which is right but when I try to set value, it creates another cookie with different domain which is automation.x.com w/o prepending " . ".
This is wierd.

**Comment by eXon** [comment]
I don't have much control over how browsers handle the cookies =(

Let me know if I can do something here but it doesn't look to me your issue is related to this library.
