### ISSUE TITLE
plugToRequest equivalent in v2?

### ISSUE THREAD

**Issue by oyeanuj** [reactivestack/cookies#131]
Hi @eXon, as I am upgrading from v1 to v2 in a SSR app, I felt a little unclear on how cookies that are `set` on the server-side are then updated on the client side? My understanding was that in v1, `plugToRequest` was achieving that.

How do you recommend achieving that with v2?

Thank you!

**Comment by eXon** [comment]
You can use [universal-cookie-express](https://github.com/reactivestack/cookies/tree/master/packages/universal-cookie-express) or write your own if you are using something else. 

It is pretty much straightforward to write, just look at the source code.
