### ISSUE TITLE
universal-cookie hooks documentation

### ISSUE THREAD

**Issue by dovidweisz** [reactivestack/cookies#133]
Is there a reason why the hooks for `onSet` and `onRemove` are not documented?

Can i safely use these in my app?

Can i submit a PR with the documentation?

**Comment by eXon** [comment]
Yes you can safely assume they are there to stick. I would happily look at your PR 👍

**Comment by eXon** [comment]
Now there is a `addChangeListener` / `removeChangeListener` that are documented and more friendly :)
