### ISSUE TITLE
Call _updateBrowserValues in the constructor?

### ISSUE THREAD

**Issue by oyeanuj** [reactivestack/cookies#135]
Hi @eXon, thank you for the library - I was able to use it successfully. The only place where I tripped up was that I noticed that in the following code, I can't use `cookiesInstance.cookies` directly:

```jsx
const cookiesInstance = new Cookies();
console.log(cookiesInstance.cookies) // <- nothing
```

So, I had to access cookies by key rather than being able to deal with an object of cookies. And it seems like the that happens because `_updateBrowserValues` is only called on `get` or `getAll` calls. It felt weird that if I print out the `cookiesInstance` above, it shows a key called `cookies` but I can't access it.

Is that intentional? Or should the `_updateBrowserValues` be really called in the constructor initially?

**Comment by eXon** [comment]
@oyeanuj You should not touch internal properties, it is not part of the documented public API. My bad for making it too obvious xD.

If you want all the cookies, you should use `getAll()` and you will get an object with everything.
