### ISSUE TITLE
cookies.set doesn't trigger components update

### ISSUE THREAD

**Issue by insolite** [reactivestack/cookies#136]
Shouldn't react-cookie use `onSet` by default to make `withCookies`-wrapped component know that cookies has changed (using `cookies` property or so)?

**Comment by eXon** [comment]
I think it's a good idea. Probably the expected behavior from a HOC.

**Comment by eXon** [comment]
If you update at `2.2.0`, `withCookies` should update as soon as a cookie is changed. You can also get them using the `allCookies` props received from the HOC.
