### ISSUE TITLE
cookie.remove doesn't consistenly remove cookies

### ISSUE THREAD

**Issue by marcuslongwell** [reactivestack/cookies#137]
I have some cookie named 'token', set like so:

```
cookies.set('token', 'asdfasdfasdf', { path: '/' });
```

And it seems as though `.remove()` doesn't actually remove the token sometimes.

```
cookies.remove('token');
console.log(cookies.get('token')); // sometimes 'asdfasdfasdf', sometimes undefined
```

Am I missing some sort of asynchronous nature or something?

**Comment by marcuslongwell** [comment]
Is it important that I include the path in my remove? i.e.:

```
cookies.remove('token', { path: '/' });
```

**Comment by davidfurlong** [comment]
Duplicate see https://github.com/reactivestack/cookies/issues/16 @marcuslongwell

**Comment by fontpiece** [comment]
cookies how to import？

**Comment by eXon** [comment]
When removing a cookie, you have to apply the same rules as when creating or updating one. Otherwise it will not be consistently removed :)
