### ISSUE TITLE
On setting httpOnly,Token Disappears from the cookie tab

### ISSUE THREAD

**Issue by blaine12100** [reactivestack/cookies#138]
Hello

I have used this library to set the value of a authorization token which i need access to my front end page so that i can verify if a user is logged in.On setting httpOnly to true,it hides the token from the cookie tab and also does not allow me to access the token on the frontend.Is there any way i can hide the token from the cookie tab but still be able to use it on my front end?

When i use the http only flag,does it set the token value or it hides the token from the cookie tab?

**Comment by eXon** [comment]
The `httpOnly` flag is there to not allow you to access the cookie within javascript. Therefore, you have to disable it if you want to access it. If you don't or can't, you can set a javascript variable when rendering the HTML page.

You can read more at https://www.owasp.org/index.php/HttpOnly

**Comment by blaine12100** [comment]
So there is now way for me to hide it from the cookies tab and still be
able to access it?

**Comment by eXon** [comment]
Nop. If you can read it with JavaScript, there is no way to hide it to everyone else. httpOnly cookies are meant to be read/write on the server only.
