### ISSUE TITLE
"Latest Release" doesn't point to latest release

### ISSUE THREAD

**Issue by manuel-jasso** [reactivestack/cookies#139]
Hi @eXon! Browsing around npm and GitHub I found that the latest release link on GitHub doesn't point to the latest release tag on npm:

https://github.com/reactivestack/cookies/releases/latest points to 1.0.4

https://www.npmjs.com/package/universal-cookie says 2.1.2

Hope this was useful, thanks!

Very good library, BTW, you take care of server and client! 👏

**Comment by eXon** [comment]
Hey @manuel-jasso 

My bad I was not using the GitHub releases, only tags. I've updated it to 2.2 and added the changelog in the release notes =)
