### ISSUE TITLE
React-cookie not including typings in build

### ISSUE THREAD

**Issue by aamctustwo** [reactivestack/cookies#141]
It appears that typings were added for `react-cookie` in PR #107 but the `index.d.ts` file was not included in the latest `npm` package (Version 2.1.4).

While the `package.json` appears correct in the latest `npm` version and points to the typings file, without the `index.d.ts` file included it cannot be typed.

**Comment by eXon** [comment]
I'm pretty sure this is solved. Let me know if it's not.
