### ISSUE TITLE
Uncaught TypeError: option expires is invalid

### ISSUE THREAD

**Issue by debabrata100** [reactivestack/cookies#142]
Hi, I am getting this error from the following code I have implemented:
import Cookies from 'universal-cookie';
const cookies = new Cookies();
.....
.....
const d = new Date();
            d.setTime(d.getTime() + (2*24*60*60*1000));
            let expires = d.toUTCString(); // Thu, 05 Apr 2018 11:03:19 GMT
            cookies.set('name', "value",
            {
              expires : expires
            }

Can someone tell what is wrong with my code???

**Comment by nabinadhikari** [comment]
I am also having same problem. It seems like it is not recognizing expires keyword at all.

**Comment by debabrata100** [comment]
@nabinadhikari  Thanks, buddy. You saved my time. :1st_place_medal:
