### ISSUE TITLE
How to run automated tests using Firefox

### ISSUE THREAD

**Issue by seth-priya** [reactivestack/cookies#145]
Hi,

Chrome is not supported on the architecture that I am using, so I tried changing
    browsers: ['firefox'],
in karma.conf.js

However, getting this error with "yarn test"
25 04 2018 15:11:25.077:INFO [karma]: Karma v2.0.2 server started at http://0.0.0.0:9876/
25 04 2018 15:11:25.081:INFO [launcher]: Launching browser firefox with unlimited concurrency
25 04 2018 15:11:25.082:ERROR [launcher]: Cannot load browser "firefox": it is not registered! Perhaps you are missing some plugin?
25 04 2018 15:11:25.082:ERROR [karma]: Found 1 load error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Tried npm install karma-firefox-launcher --save-dev

However, that does not help.

Any pointers here would be of great help, thanks!

Regards,
Priya

**Comment by eXon** [comment]
Hi there,

This is because you are missing the [karma-firefox-launcher](https://www.npmjs.com/package/karma-firefox-launcher) NPM package. Let me know if you're still having troubles.

**Comment by tbounsiar** [comment]
do not forget require('karma-firefox-launcher') in karma config plugins.

**Comment by AndrewWay** [comment]
Running `npm install karma-firefox-launcher --save-dev` and then including `require('karma-firefox-launcher')` under the plugins array in karma.conf.js worked for me
