### ISSUE TITLE
Firefox not Recognizing Cookies set from Other Tab Until a Refresh

### ISSUE THREAD

**Issue by BigPrimeNumbers** [reactivestack/cookies#148]
While using FF, when I have two tabs running my app running from the same site, if I set/remove a cookie in one tab, the other tab does not recognize this change (i.e. from the dev console, cookie storage does not show the change) unless I refresh it. This is a huge problem with logging in/out from one tab while the app is open in multiple tabs.

Is this a shortcoming of FF, or an issue with this package? 

Thanks!

**Comment by eXon** [comment]
Hi @BigPrimeNumbers 

How are you checking if the cookie has been changed? Is your cookie value is stalled with the old one even though it has been changed by another tab?

**Comment by BigPrimeNumbers** [comment]
I check by both polling the current value from JS, and by checking the cookies in the developer window of the browser. It's just as you said, when tab A updates a cookie in, that update (wether it's adding, deleting, or updating a value) does not show in other tabs until they are refreshed.

After doing some tests, it appears to be an idiosyncrasy of FF, one that I don't remember it having prior. It could be part of their security update they rolled out to deal with FB, and I hadn't noticed until recently.

**Comment by eXon** [comment]
Hi @BigPrimeNumbers 

Is there anything we can fix? If not, please close the issue.

Thank you!

**Comment by BigPrimeNumbers** [comment]
Unfortunately probably not at this point, though I'm curious if others are running into similar issues - I can't imagine I'm the only person using cookies across tabs.

I'll close this for now, unless someone has something to add, or this package has some way of addressing this oddity.
