### ISSUE TITLE
import Cookie needs to be import * as Cookie in Typescript

### ISSUE THREAD

**Issue by flyon** [reactivestack/cookies#152]
just a heads up: usually I can just copy paste the example import statement of a library to my TS project, but in this case I had to change to `import * as Cookie from universal-cookie`. Not sure why

**Comment by eXon** [comment]
Hey thank you for reaching! This is a pretty common thing for libraries, even React has this problem. I don't think it needs to be changed on the readme though because TypeScript developers learn about that issue pretty much day 1.
