### ISSUE TITLE
cookie returned to browserin XHR response but not present on refresh

### ISSUE THREAD

**Issue by flyon** [reactivestack/cookies#153]
Using React & Express.js, the examples were not enough for me. 
Took me a while before I figured out I had to do the following on the serverside (after installing the middleware) to make it work:

    req.universalCookies.set('name','value', { domain:req.headers.origin,path: '/' });

**Comment by eXon** [comment]
Have you tried to only include the path? It's pretty much the first time I see this problem.

**Comment by flyon** [comment]
ok, it's now also not working with the code I posted above, something else must be going on.

My server setup:

	import * as cookiesMiddleware from 'universal-cookie-express';
	....
	this.app = express();
	this.app.use(cookiesMiddleware());

When a login request turns out to be successful at the server:

	req.universalCookies.set('cdlAuth', hash, { path: '/' });

The response in the chrome debugger Network tab shows that a cookie was returned

![image](https://user-images.githubusercontent.com/341567/41566702-495c2e84-7322-11e8-94a6-d1bb43b903d7.png)

However in the Application tab under cookies I don't see it listed, even after pressing the refresh button in that panel.

![image](https://user-images.githubusercontent.com/341567/41566723-5dc05332-7322-11e8-9019-cbc8d35f3581.png)

When I refresh there is no cookie found:

    const Cookies = require("universal-cookie");
    //....
    componentWillMount() {
        const cookies = new Cookies();
        var hash= cookies.get('cdlAuth');
        if (hash) {
             //this doesnt trigger on refresh
       }

Ive turned off any plugin that may be blocking the cookies, and I've tried adding a domain as posted initially. Any idea what Im doing wrong?

**Comment by eXon** [comment]
@flyon It looks like your cookie is being set on your AJAX domain, which is different than your Website domain am I right? 

If you don't need the data and only need to save it for subsequent requests, you can use the `withCredentials` option. This is by far better if it needs to be secure. You might want to use httpOnly cookies too.

If you really need the data, I would suggest returning it somewhere in the body or header of the request and then saving it in the cookies in JavaScript.

Hope it helps

**Comment by flyon** [comment]
@eXon I think the domains are the same, but I switched to setting the cookie in the browser, and that works. Thanks!
