### ISSUE TITLE
TypeError: Cannot read property 'addChangeListener' of undefined

### ISSUE THREAD

**Issue by illuminardy** [reactivestack/cookies#155]
Get the following error when using v2.2.0:

TypeError: Cannot read property 'addChangeListener' of undefined which was committed 3 days ago.

**Comment by eXon** [comment]
My bad, I've not updated the TypeScript typing yet. I'll try to do that this week.

**Comment by Zukzuk** [comment]
+1

**Comment by abusada** [comment]
Hello, any updates here? i have the same issue

**Comment by davorbuha** [comment]
not solved yet?

**Comment by vinicri** [comment]
+ 1

**Comment by eXon** [comment]
I'm going to do that new week, I'm out of town right now. Sorry about the delay

**Comment by eXon** [comment]
Should be fixed in `v3.0.0`
