### ISSUE TITLE
[react-cookie] Update hoist-non-react-statics package

### ISSUE THREAD

**Issue by sergei-zelinsky** [reactivestack/cookies#157]
Hi!

Get the warning when using `getDerivedStateFromProps` inside wrapped component:

```
Warning: withCookies(Component): Did not properly initialize state during construction. Expected state to be an object, but it was undefined.
```
According to [the PR](https://github.com/mridgway/hoist-non-react-statics/pull/43) `hoist-non-react-statics` should be updated to the last version to fix the warning.

Thanks!

**Comment by eXon** [comment]
Fixed in `v3.0.0`
