### ISSUE TITLE
Unable to set a Cookie domain

### ISSUE THREAD

**Issue by Roger13** [reactivestack/cookies#162]
I'm basically trying to set a cookie to a domain and all subdomains. 

`cookies.set('m_tokenId', response.tokenId, {domain: '.test.com'});`

Unfortunately, when i try to set a domain option, the cookie is not even created. I'm trying to make it available to the following domains:
```
'blabla-web.test.com'
'blabla-api.test.com'
```

**Comment by Roger13** [comment]
I'm only allowed to set a domain based on my server one. Since I was running from localhost, I was unable to set the cookie under the desired domain.

**Comment by schakraborty2050** [comment]
what if my application and APIs runs on different server? for eg. my application is on text.com and APIs are on AWS lambda?

**Comment by Roger13** [comment]
@schakraborty2050 If your lambda need access to those cookies, you can either expose them from your application server or set a common base domain, such as app-api.organization.com (for your lambdas) and app-web.organization.com (for your application)

**Comment by eXon** [comment]
@dimblek7 This is not a bug, it is how cookies are working on the browser. You can only set cookies on the same domain as you are. You can allow any subdomain to access the same cookie by using `{domain: '.test.com'}`, but it would not work if you are not on test.com. To test that locally, you have to set 127.0.0.1 on a domain into your host file. (see https://support.rackspace.com/how-to/modify-your-hosts-file/)
