### ISSUE TITLE
TypeError after installation

### ISSUE THREAD

**Issue by stefankp** [reactivestack/cookies#163]
Hi, 
just installed `react-cookie` and got this error:

```
TypeError: Cannot convert undefined or null to object

hoistNonReactStatics
node_modules/hoist-non-react-statics/dist/hoist-non-react-statics.cjs.js:40
  37 | if (typeof sourceComponent !== 'string') { // don't hoist over string (html) components
  38 | 
  39 |     if (objectPrototype) {
> 40 |         var inheritedComponent = getPrototypeOf(sourceComponent);
  41 |         if (inheritedComponent && inheritedComponent !== objectPrototype) {
  42 |             hoistNonReactStatics(targetComponent, inheritedComponent, blacklist);
  43 |         }
```

<img width="656" alt="image" src="https://user-images.githubusercontent.com/3661203/44157382-9c32d500-a0b2-11e8-84cd-35339924ab07.png">

Any idea how to get `react-cookie` working properly?

**Comment by eXon** [comment]
Can you be more specific on the steps to reproduce? I haven't seen this error before. Also, what version are you using? It is through NPM or GitHub?

**Comment by stefankp** [comment]
I installed the package from Yarn (https://yarnpkg.com/en/package/react-cookie) and followed the example here https://github.com/reactivestack/cookies/tree/master/packages/react-cookie#simple-example: 
- Add the `CookiesProvider`
- Add `export default withCookies(App);`

The error occurs after adding `withCookies`.

**Comment by stefankp** [comment]
@eXon I got the latest version and tried again. Now I am getting this error:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/3661203/44274643-f2368280-a242-11e8-8621-8913aaea711f.png">

**Comment by eXon** [comment]
@stefankp Would you mind sharing your code? It looks like `WrapperComponent` is undefined, which should never be on a decorator

**Comment by stefankp** [comment]
@eXon that one was actually on me. Doesn't work with `compose`:

```
export default compose(
  withRouter,
  translate(),
  withCookies(),
)(App);
```

This works fine:
```
export default withCookies(App);
```

**Comment by eXon** [comment]
@stefankp Removing the parenthesis of withCookies should make it work

**Comment by stefankp** [comment]
It does, thank you. The initial error got fixed with the new release, so we can close this 👍
