### ISSUE TITLE
universal-cookie-express v3.0.0 is broken without TypeScript

### ISSUE THREAD

**Issue by yury** [reactivestack/cookies#164]
Try to use it without TypeScript as in readme. And got error - cookiesMiddleware is not a function.

**Comment by eXon** [comment]
I wasn't aware that when targeting CommonJS with TypeScript, it wasn't handling default export properly (you had to add .default). Fixed in `3.0.1`.

Let me know if it works!

**Comment by yury** [comment]
Nope, still doesn't work for me :(

**Comment by eXon** [comment]
My bad I don't know how my tests were working before. Let me know if `3.0.3` is working!

**Comment by yury** [comment]
v3.0.3 is ok.
Thank you.
