### ISSUE TITLE
clarify react peer dependency in Readme

### ISSUE THREAD

**Issue by LuiSlacker** [reactivestack/cookies#165]
Please state in the Readme, that the latest version needs react >= 16.3, otherwise the error `React.createContext is not a function` causes the app to crash.

**Comment by eXon** [comment]
It's a pretty big breaking change you're right. I've added a [new section in the readme for the minimum requirement](https://github.com/reactivestack/cookies/tree/master/packages/react-cookie#minimum-requirement).

Do you think it is clear enough with that?

**Comment by LuiSlacker** [comment]
Perfect. That'll do. Thanks
