### ISSUE TITLE
universal-cookie-express v3.0.1 break the session

### ISSUE THREAD

**Issue by idangozlan** [reactivestack/cookies#166]
Hi,

I was using universal-cookie-express ^2.1.5, upgraded to latest and now express session or csrf (both using redis, if it's matter) are not working, so req.session is always undefined..

Is there any breaking changes? there's no error on screen..

**Comment by eXon** [comment]
That version was unfortunally broken. If you upgrade universal-cookie, universal-cookie-express and react-cookie (if using it) to `3.0.3` and it should work and be 100% retro-compatible outside of the undocumented hooks on the `Cookies` constructor. However, you need React >= 16.3.0 if you are using react-cookie.

Let me know if it works and if not, would you mind sharing some code to reproduce?
