### ISSUE TITLE
CookieSetOptions interface is missing sameSite option

### ISSUE THREAD

**Issue by Equationist** [reactivestack/cookies#168]
sameSite option is probably supported since cookie is used behind the scenes, and it supports the sameSite option: https://github.com/jshttp/cookie/blob/master/index.js#L159

**Comment by eXon** [comment]
Thank you for noticing this. It has been added and will be in the next release.

**Comment by eXon** [comment]
@Equationist Can you confirm your issue has been fixed in `v3.0.4`? Thank you!

**Comment by Equationist** [comment]
Yes, it's fixed. Thanks for the prompt push!
