### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [reactivestack/cookies#169]
I just saw the packages are updated from `v2.2.0` to `v3.0.4` which implies breaking changes, but I can't find any CHANGELOG to check them out.

Would you guys be so kind to provide us with a decent CHANGELOG for every package (or just a general one), please? 🙂

Thanks for all your hard work! 🙂

**Comment by eXon** [comment]
Yea I think a changelog is long overdue. There is not much breaking changes in `v3` outside of react-cookie that requires react >= 16.3 and you cannot use universal-cookie 2 with react-cookie 3. Also an undocumented hook in Cookie constructor that disappear.

I'll add one so we can track changes on every version.

**Comment by eXon** [comment]
This should do the trick: https://github.com/reactivestack/cookies/blob/master/CHANGELOG.md

Let me know if you think something is missing!

**Comment by MichaelDeBoey** [comment]
Hi @eXon!

Thanks for the CHANGELOG!  🙂

This helps a lot when upgrading. 😉
