### ISSUE TITLE
SameSite

### ISSUE THREAD

**Issue by 2ajoyce** [reactivestack/cookies#171]
Is it possible to set the SameSite option on a cookie, and if so, how do I do it? I didn't see it listed under the [set options](https://github.com/reactivestack/cookies/tree/master/packages/react-cookie/#setname-value-options).

**Comment by eXon** [comment]
Yes the option is supported and was missing in the TypeScript typing until the last version. I've updated the readme with the information. Thank you for letting me know! 👍
