### ISSUE TITLE
Cookies access in side action file.

### ISSUE THREAD

**Issue by charithAmila** [reactivestack/cookies#173]
Hi 
How i access (set or get) cookies in side action file.

Thank you .

**Comment by eXon** [comment]
@charithAmila Are you using `unviersal-cookie` or `react-cookie`? If you are using `universal-cookie` it is straightforward (just an import), but if you are using `react-cookie`, you need to pass the `cookies` prop using `withCookies` to your redux actions or whatever you are using.

**Comment by charithAmila** [comment]
I am using react-cooke.
Thank you @eXon
