### ISSUE TITLE
Testing subdomain cookie - by adding domain option , caused cookie not saved

### ISSUE THREAD

**Issue by isuhendro** [reactivestack/cookies#179]
As mentioned here https://stackoverflow.com/questions/18492576/share-cookie-between-subdomain-and-domain , I must add domain = `.mydomain.com` so that a cookie can be made available to `subdomain1.mydomain.com` or `subdomain2.mydomain.com`

Thus I started to test in my localhost
`this.props.cookies.set("hello", "there");`
it works.

Adding any domain like below will make the cookie **never got saved**
`this.props.cookies.set("hello", "there", {domain: "localhost"});`
`this.props.cookies.set("hello", "there", {domain: ".localhost");`

Any suggestion? Thanks.

**Comment by eXon** [comment]
`localhost` is a special case. Because it doesn't include a dot, the browser is denying it. You can use lvh.me instead of localhost (or any DNS entry pointing to 127.0.0.1). Otherwise you can omit the parameter only when working in development.

**Comment by isuhendro** [comment]
Super @eXon. Thanks for the answer and wonderful util.

**Comment by mstfymrtc** [comment]
@eXon although i work with lvh.me, i got same issue. If I set cookie to ".domain.com" it's ok but when i want to set cookie for "subdomain.domain.com" from another subdomain, i failed.  What should i do?

**Comment by zamson** [comment]
@mstfymrtc did you find a solution?

**Comment by mstfymrtc** [comment]
No, I couldn't. @zamson
