### ISSUE TITLE
I extended the universal cookie middleware to support hapijs

### ISSUE THREAD

**Issue by J0NNYZER0** [reactivestack/cookies#181]
I prefer @hueniverse hapijs framework over express, so I extended this for that. If you would like I can send you the code or do a pull request and can covert it to typescript.

I will probably need a couple rounds of edits to get it where you approve but this would be helpful for developers who are doing isomorphic react with a hapi server.

There are some big differences you need to understand with the way hapi manages cookies. Hapi has an h interface which I use to set and unset server state.

If you have any questions hollar back.

Let me know what you'd like me to do.

**Comment by eXon** [comment]
I would be happy take a look at your PR if you would like to create `universal-cookie-hapijs` and make it official. You can even publish on your own if you would like.

**Comment by J0NNYZER0** [comment]
I would love to share the code but I am really busy with a lot of other stuff at the mo'. Give me some time and I will share the code with you via a PR. Just give me a week or so.

**Comment by apascal** [comment]
Hi @J0NNYZER0 when do you think you will be able to share this ? We also investigate using Hapi with isomorphic react rendering and would love to be able to deal with cookies the same way we did with Express.
