### ISSUE TITLE
CookiesProvider will not render

### ISSUE THREAD

**Issue by anking** [reactivestack/cookies#184]
In my index.js for react app I have the following:

```
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/css/bootstrap-theme.css';
import './index.css';
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
//cookie
import { CookiesProvider } from 'react-cookie';


const baseUrl = document.getElementsByTagName('base')[0].getAttribute('href');
const rootElement = document.getElementById('root');

ReactDOM.render(
    <CookiesProvider>
        <BrowserRouter basename={baseUrl}>
            <App />
        </BrowserRouter>
    </CookiesProvider>
    ,
    rootElement);

registerServiceWorker();
```

But it produces the following error:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `CookiesProvider`.
▶ 26 stack frames were collapsed.
Module../src/index.js
C:/dev/DigiSign/DigiSign2018_UAT/SimplySignWeb/v7/ClientApp/src/index.js:23
  20 | //const rootReducer = combineReducers({});
  21 | //const store = createStore(rootReducer, {});
  22 | 
> 23 | ReactDOM.render(
  24 |     <CookiesProvider>
  25 |         <BrowserRouter basename={baseUrl}>
  26 |             <App />
View compiled
__webpack_require__
C:/dev/DigiSign/DigiSign2018_UAT/SimplySignWeb/v7/ClientApp/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
```

Am i missing something?

**Comment by anking** [comment]
Here is dependencies out of my package.json:
  "dependencies": {
    "bootstrap": "^3.3.7",
    "react": "^16.5.2",
    "react-addons-css-transition-group": "^15.6.2",
    "react-bootstrap": "^0.31.5",
    "react-cookie": "^3.0.4",
    "react-dom": "^16.0.0",
    "react-redux": "^5.0.7",
    "react-router-bootstrap": "^0.24.4",
    "react-router-dom": "^4.2.2",
    "react-scripts": "^2.0.4",
    "react-text-mask": "^5.4.3",
    "redux": "^4.0.0",
    "rimraf": "^2.6.2"

**Comment by eXon** [comment]
@anking Do you still have the issue? It looks like your version of React doesn't have the last context API, which is starting from 16.3. I know in your package.json says 16.5, but can you check the actual installed version in your node_modules?

**Comment by eXon** [comment]
I've tried to replicate the problem but have not been able. Would you be able to provide a sandbox with the bug? Thank you

**Comment by eXon** [comment]
Close due to inactivity. Let me know if it's still an issue.
