### ISSUE TITLE
Cannot use 'new' with an expression whose type lacks a call or construct signature.

### ISSUE THREAD

**Issue by chj-damon** [reactivestack/cookies#186]
I'm using `universal-cookie` in typescript. Here is my code:
```typescript
import * as Cookies from 'universal-cookie';
const cookies = new Cookies({});
```
in `index.d.ts`:
```typescript
import Cookies from './Cookies';
export default Cookies;
export * from './types';
```
`export default Cookies` means I don't have to use `import * as` but I can just import `Cookies` like this: `import Cookies from 'universal-cookie'`;
But if I do so, I got an error:
`Cannot use 'new' with an expression whose type lacks a call or construct signature.`

**Comment by jsphweid** [comment]
@chj-damon how did you solve this?

**Comment by stubar** [comment]
I am getting this error in 3.0.7 if I 

``` import Cookies from "universal-cookie";```
only way I can get working is to 

```import Cookies from "universal-cookie/es6/Cookies"; ```
