### ISSUE TITLE
universal cookies reports error in jest test case

### ISSUE THREAD

**Issue by chj-damon** [reactivestack/cookies#187]
I'm using universal-cookie in typescript. When I try to test my code within cookies, it reports an error:
```typescript
universal_cookie_1.default is not a constructor
```
Here's how I use it in my code:
```typescript
import Cookies from 'universal-cookie';
const cookies = new Cookies({});
```
and it works fine in the development environment. 
I have no idea why it failed in the test case.

**Comment by mattnedrich** [comment]
I'm seeing the same issue

**Comment by mattnedrich** [comment]
Adding `esModuleInterop: true` to `tsconfig.json` fixed this issue for me.

**Comment by eXon** [comment]
If you add the `esModuleInterop` setting it should fix the issue. universal-cookie is built into CommonJS module and it is why you have the error.
