### ISSUE TITLE
Get cookie for specific path

### ISSUE THREAD

**Issue by SachaG** [reactivestack/cookies#188]
I have a situation where for whatever reason, I ended up with two cookies for the same `/foo` page. One for path `/foo` and one for path `/`. 

I would like the `/` cookie to be used, not the `/foo` cookie. But I can't find a way to specify which cookie to use? The `path` option doesn't seem to work fro `cookies.get()`?

And `cookies.getAll` doesn't show me the cookie for `/`, only the one for `/foo`.

**Comment by SachaG** [comment]
Oh and also I think like the cookie used during the SSR process is somehow different (so it's `/`, not `/foo`) because I'm seeing a mismatch between SSR and browser content.

**Comment by eXon** [comment]
Unfortunately you or the library has no control over this. It's all managed by the browser. If you make sure to specify the `path` when you set your cookies everywhere, it should not be a problem. Most of the time, you just want `{ path: '/' }` everywhere unless you have a very specific reason. It needs to be done when setting your cookies, not getting them. Is it included everywhere?

**Comment by SachaG** [comment]
Yes, I think now I'm specifying the path everywhere, so it was probably an older cookie that was still remaining.

**Comment by eXon** [comment]
Ok, let me know if you think it's still a bug.
