### ISSUE TITLE
Idea: remove() returns promise

### ISSUE THREAD

**Issue by amacrobert** [reactivestack/cookies#189]
Ran into an issue where when the user logged out, I was removing a cookie and immediately redirecting like so:

    import Cookies from 'universal-cookie';

    logout = () => {
        let cookies = new Cookies();
        cookies.remove('AUTH-TOKEN');
        window.location.href = '/';
    };

Often the redirect would happen before the cookie was finished removing, meaning the user was still logged in after the page load. I'm temporarily putting the window.location in a 100ms timeout, but I think a nice solution would be fore remove() to return a promise so I could write it like this:

    import Cookies from 'universal-cookie';

    logout = () => {
        let cookies = new Cookies();
        cookies.remove('AUTH-TOKEN').then(() => {
            window.location.href = '/';
        });
    };

**Comment by eXon** [comment]
I like the idea of the Promise. It would need to use polling to make sure the cookie has been removed. I'm not sure how to check that properly, I'll need to do some research.

**Comment by tresdev** [comment]
This would be really useful in situation like this. I'm also using timeout like this, and it's not really a preferred way.

**Comment by Asher978** [comment]
Same issue as above. 
Redirect occurs before the cookie is removed. Thus the user still stays authenticated.

**Comment by Asher978** [comment]
This is my go around this for now. Can something like this be implemented in your lib?

``` javascript

/**
 *
 * @param {String} name
 * promisfy the remove cookie
 */
export const removeCookie = name => {
  // promisfy the body of func by returning a promise
  return new Promise((resolve, reject) => {
    // check to see if a proper cookie name was provided
    if (name && typeof name === "string") {
      // remove the cookie
      cookie.remove(name)

      // check if cookie was removed from the browser
      // getAll() will return an object containing current browser's cookies
      const currBrowserCookies = cookie.getAll()

      // check if token was removed
      const userCookieExist = currBrowserCookies.hasOwnProperty(name)

      userCookieExist
        ? reject(new Error("Your cookie still exist!"))
        : resolve({ message: "Your cookie was removed :)" })
       
    } else {
      // encounter invalid parameter 
      // (name was not a string) || (name === undefined)
      // return reject
      reject(new Error("Cookie name provided is invalid!"))
    }
  })
}


```

**Comment by eXon** [comment]
This will not be implemented because it is out of scope for the library.Thanks for your suggestion.
