### ISSUE TITLE
TypeScript type of withCookie does not take into account other HoCs

### ISSUE THREAD

**Issue by steelfinger** [reactivestack/cookies#190]
The type definition of withCookies can't handle situations where there are multiple HoCs applied to one component. For instance: `withCookies(withRouter(App))`. It needs quite a complex typing to handle these situations but there are libraries where it's done right, for instance react-router. Here's more information on subject: [React Higher-Order Components in TypeScript](https://medium.com/@jrwebdev/react-higher-order-component-patterns-in-typescript-42278f7590fb)

**Comment by Laterality** [comment]
I got this problem too, and solved **temporarily** by modifying:

node_modules/react-cookie/cjs/withCookies.d.ts
```
// ...
export default function withCookies<T extends ReactCookieProps>(WrapperComponent: React.ComponentType<T>): React.ComponentType<T>;
```

But, the repo's code is already changed like above. I guess that modified version is not published to npm.

**Comment by eXon** [comment]
Release in v3.0.5
