### ISSUE TITLE
Potential memory leak with Server Side Rendering

### ISSUE THREAD

**Issue by jonatansberg** [reactivestack/cookies#191]
Hi!
We have been experiencing issues with memory leaks in one of our production apps where we use `react-cookie`, `universal-cookie` and `universal-cookie-express`.

When doing server side rendering any children to a `withCookies()` HOC will leak due to the way that  change listeners are set up. The problem is that `componentWillUnmount` in `CookieWrapper` never triggers on the server, meaning the subscription is set up in `render()` will never get cleaned up, creating a leak.

A possible solution would be to just read the values of the cookies on the sever instead of creating a subscription. Providing a teardown method that can be called after completing rendering that would clear up all subscriptions could also work.

I think we will try to look in to this further in the coming days, so any input would be greatly appreciated!

**Comment by eXon** [comment]
I think the listener should be added on the `componentDidMount`/`componentDidUpdate`. I'm pretty sure it would fix the leak. I'll need to take a look at it.

**Comment by eXon** [comment]
Released in v3.0.7
