### ISSUE TITLE
Missing module files in publish react-cookie package v3.0.5 

### ISSUE THREAD

**Issue by Quramy** [reactivestack/cookies#193]
Hi.

It seems that the latest react-cookie package is broken. It does not include `cjs/index.js` nor `es6/index.js` files, which are listed package.json files section.

The following installed files by `npm i react-cookie` at my local machine.

```txt
- react-cookie/                       
 |- lib/                              
  |  Cookies.js                       
  |  CookiesProvider.js               
  |  index.js                         
  |  withCookies.js                   
 |  index.d.ts                        
 |  package.json                      
 |  README.md                         
```

**Comment by stefensuhat** [comment]
+1. downgrading to 3.0.4 works fine.

**Comment by eXon** [comment]
My mistake, I'll publish a new version ASAP

**Comment by eXon** [comment]
@Quramy @willdurand @stefensuhat 

It should be fixed in `v3.0.6`. Can you confirm?

**Comment by dammitmoonmoon** [comment]
I can, the updated package works just fine. Thanks for fixing it so fast!

**Comment by Quramy** [comment]
I've checked too and it works well. Thanks :)

**Comment by willdurand** [comment]
Same here, thanks!
