### ISSUE TITLE
Required attributes

### ISSUE THREAD

**Issue by oskarleonard** [reactivestack/cookies#194]
When using CookiesProvider on the client im getting these warnings

- Element CookiesProvider doesn't have required attribute allCookies
- Element CookiesProvider doesn't have required attribute cookies

Are these props really required? In the examples nothing is passed in to CookiesProvider on the client.

**Comment by eXon** [comment]
No it was a mistake. Let me know if it's fixed in 3.0.7

**Comment by oskarleonard** [comment]
No warning anymore :)
