### ISSUE TITLE
CHANGELOG for v3.0.6 missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [reactivestack/cookies#195]
I just saw the package is updated to `v3.0.6`, but I can't find any records in the CHANGELOG to check out the changes.

Would you guys be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work! 🙂

Duplicates #169

**Comment by eXon** [comment]
For some reason the changelog was lost. `3.0.6` had no change, only fixed the missing files in the build.

**Comment by eXon** [comment]
Updated: https://github.com/reactivestack/cookies/blob/master/CHANGELOG.md
