### ISSUE TITLE
TypeScript complaining of CookiesProvider type

### ISSUE THREAD

**Issue by dbrrt** [reactivestack/cookies#196]
After updating to 3.0.6, I've got the following message :
TS2322: Type '{ children: Element; }' is not assignable to type 'Readonly<ReactCookieProps>'.

Rolling back to 3.0.4 solved the issue, but it'd be nice to figure out what's happening there.

**Comment by eXon** [comment]
It was a mistake. Let me know if this is fixed in 3.0.7

**Comment by nsorauf** [comment]
Still not working for me, I'll post details in a new issue

**Comment by dbrrt** [comment]
It's all good in 3.0.7 ! Thanks for the fix.
