### ISSUE TITLE
Typescript complains about missing 'cookies' property in 3.0.7

### ISSUE THREAD

**Issue by nsorauf** [reactivestack/cookies#198]
TS gives the following error (with no props in CookiesProvider):
`      TS2345: Argument of type 'ConnectedComponentClass<typeof PageBody, Pick<any, string | number | symbol>>' is not assignable to parameter of type 'ComponentType<Pick<any, string | number | symbol> & WrapperProps>'.
  Type 'ConnectedComponentClass<typeof PageBody, Pick<any, string | number | symbol>>' is not assignable to type 'ComponentClass<Pick<any, string | number | symbol> & WrapperProps, any>'.
    Types of property 'propTypes' are incompatible.
      Type 'ValidationMap<Pick<any, string | number | symbol>> | undefined' is not assignable to type 'ValidationMap<Pick<any, string | number | symbol> & WrapperProps> | undefined'.
        Type 'ValidationMap<Pick<any, string | number | symbol>>' is not assignable to type 'ValidationMap<Pick<any, string | number | symbol> & WrapperProps>'.
          Property 'cookies' is missing in type 'ValidationMap<Pick<any, string | number | symbol>>'.`

**Comment by dbrrt** [comment]
Do you have an example to reproduce this? I've had similar problem in 3.0.6 which was fixed with `3.0.7` #196

**Comment by eXon** [comment]
I reverted a breaking change I wasn't aware of. Can you try v3.0.8 and let me know if it has been fixed?
