### ISSUE TITLE
Problem with Internet Explorer

### ISSUE THREAD

**Issue by edimarproenca** [reactivestack/cookies#203]
I have a problem using internet explorer, when I use the cookie.get ('cookieName') this returns undefined and the application crashes.

**Comment by eXon** [comment]
I've tested IE11 and it seems to work pretty well. Can you provide a sandbox with crashing code?

**Comment by smashercosmo** [comment]
@edimarproenca maybe you're trying to access http-only cookie

**Comment by eXon** [comment]
Close due to inactivity. Let me know if it's still an issue.
