### ISSUE TITLE
react-cookie 3.08 error: cookies.getAll is not a function

### ISSUE THREAD

**Issue by jalutz** [reactivestack/cookies#204]
Currently have react version 16.7.0, just updated react-cookies to 3.0.8. After updating and restarting client, getting above error and UI doesn't load. Screenshot attached. Thank you

<img width="1281" alt="screen shot 2019-01-30 at 10 29 59 am" src="https://user-images.githubusercontent.com/16255508/51992013-455f6300-247a-11e9-8225-cd6abbe57451.png">

**Comment by 010100100000** [comment]
I am having the same problem...

**Comment by richardvaldiviesomacias** [comment]
What a coincidence me too.

**Comment by eXon** [comment]
I've tried to replicate the problem but have not been able. Would you be able to provide a sandbox with the bug? Thank you

**Comment by eXon** [comment]
Close due to inactivity. Let me know if it's still an issue.

**Comment by devilcoders** [comment]
I have the same issue, while using it with Next.js

**Comment by a1p4ca** [comment]
I have the same issue

**Comment by faizrr** [comment]
To make this library work with Next.js, make `pages/_app.js` with following content:

```jsx
import React from "react";
import App, { Container } from "next/app";
import { CookiesProvider, Cookies } from "react-cookie";

const isBrowser = () => typeof window !== "undefined";

class MyApp extends App {
  static getCookies(ctx) {
    if (ctx && ctx.req && ctx.req.headers.cookie) {
      return new Cookies(ctx.req.headers.cookie);
    }

    return new Cookies();
  }

  static async getInitialProps({ Component, ctx }) {
    let pageProps = {};

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }

    const cookies = this.getCookies(ctx);

    return { pageProps, cookies };
  }

  render() {
    const { Component, pageProps, cookies } = this.props;

    return (
      <Container>
        <CookiesProvider cookies={isBrowser() ? undefined : cookies}>
          <Component {...pageProps} />
        </CookiesProvider>
      </Container>
    );
  }
}

export default MyApp;
```

**Comment by nnishimura** [comment]
Same here. This error occurs with react@16.7 and above, downgrading to react@16.6 resolved the issue

I haven't managed to reproduce this on sandbox

```
[Error] render error TypeError: Cannot read property 'getAll' of undefined
    at CookieWrapper.render (/Users/naoko/work/git/myproject/node_modules/react-cookie/cjs/withCookies.js:121:32)
    at /Users/naoko/work/git/myproject/server/webpack:/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:30:227
    at y (/Users/naoko/work/git/myproject/server/webpack:/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:30:432)
    at e.HBEh.e.render (/Users/naoko/work/git/myproject/server/webpack:/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:365)
    at e.HBEh.e.read (/Users/naoko/work/git/myproject/server/webpack:/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:442)
    at renderToString (/Users/naoko/work/git/myproject/server/webpack:/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:47:73)
    at /Users/naoko/work/git/myproject/server/webpack:/server.jsx:175:26
    at tryCatch (/Users/naoko/work/git/myproject/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:196:12)
    at invokeCallback (/Users/naoko/work/git/myproject/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:211:13)
    at /Users/naoko/work/git/myproject/node_modules/es6-promise/dist/lib/es6-promise/then.js:24:16
    at flush (/Users/naoko/work/git/myproject/node_modules/es6-promise/dist/lib/es6-promise/asap.js:98:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by SimeonC** [comment]
I set up some sandboxes to try to play with this as we are getting the error as well, but it looks like it may just be something to do with each setup rather than react-cookie itself.

Sandbox for Next.js with @faizrr code (misread the comment so thought I'd share anyway). https://codesandbox.io/s/reactcookie-204-nextjs-35qzm

Express.js SSR variant: https://codesandbox.io/s/reactcookie-204-expressjs-tr9yt

I can't replicate this in any environment so I guess it's something to do with our setup.

**Comment by jhenriquevissotto** [comment]
I have the same problem Too!!!!!

**Comment by jhenriquevissotto** [comment]
> To make this library work with Next.js, make `pages/_app.js` with following content:
> 
> ```js-jsx
> import React from "react";
> import App, { Container } from "next/app";
> import { CookiesProvider, Cookies } from "react-cookie";
> 
> const isBrowser = () => typeof window !== "undefined";
> 
> class MyApp extends App {
>   static getCookies(ctx) {
>     if (ctx && ctx.req && ctx.req.headers.cookie) {
>       return new Cookies(ctx.req.headers.cookie);
>     }
> 
>     return new Cookies();
>   }
> 
>   static async getInitialProps({ Component, ctx }) {
>     let pageProps = {};
> 
>     if (Component.getInitialProps) {
>       pageProps = await Component.getInitialProps(ctx);
>     }
> 
>     const cookies = this.getCookies(ctx);
> 
>     return { pageProps, cookies };
>   }
> 
>   render() {
>     const { Component, pageProps, cookies } = this.props;
> 
>     return (
>       <Container>
>         <CookiesProvider cookies={isBrowser() ? undefined : cookies}>
>           <Component {...pageProps} />
>         </CookiesProvider>
>       </Container>
>     );
>   }
> }
> 
> export default MyApp;
> ```

This works for me!! =DD
