### ISSUE TITLE
Get the Expire time of the cookies.

### ISSUE THREAD

**Issue by rammanoj** [reactivestack/cookies#205]
I have a cookie stored in my localhost, apart of the value of the cookie I want to get some other values like "expires" or "created on" etc. I tried this using **cookie.get()** method. But this method is only returning the value of the cookie and not returning the other details. Is there any way to get the other details except the cookie value? (went through the docs, but could not find anything better).

**Comment by daytonmills** [comment]
According to #67 

> The browser is handling how cookies are expiring. If they have, they are going to be automatically removed.

**Comment by eXon** [comment]
You cannot know when a cookie expire, but you can save the date/time into another cookie value.
