### ISSUE TITLE
When can `cookie` prop be undefined?

### ISSUE THREAD

**Issue by pokonski** [reactivestack/cookies#208]
According to this TypeScript definition https://github.com/reactivestack/cookies/blob/master/packages/react-cookie/src/types.ts#L4

`cookies` prop can be undefined, but in practice it's always there. Can we remove `?` from the definition or am I missing some crucial step in the lifecycle?

**Comment by eXon** [comment]
You don't need to specify the value on the browser, only on the server. Thus, it is optional.
