### ISSUE TITLE
Cannot use 'new' with an expression whose type lacks a call or construct signature

### ISSUE THREAD

**Issue by stubar** [reactivestack/cookies#211]
Sorry to bring up an issue that is already closed.

I am getting this typescript error in 3.0.7 if I

``` import Cookies from "universal-cookie"; ```
only way I can get working is to

``` import Cookies from "universal-cookie/es6/Cookies"; ```

**Comment by eXon** [comment]
Is this still an issue with the last version?

**Comment by matthewlein** [comment]
Yes, just installed `"universal-cookie": "3.1.0"` with this problem.

**Comment by matthewlein** [comment]
also `TESTING_ONETWO ` was left in :) https://github.com/reactivestack/cookies/blob/a380d2dcef0babf9fc7af4c54698380682096e63/packages/universal-cookie/src/Cookies.ts#L21

**Comment by eXon** [comment]
It is a default export so you must use the import without the * (star). Otherwise, you would get the named exports only.

`import Cookies from 'universal-cookie';` is the correct way and should work. Would you mind sharing your tsconfig?

**Comment by mach-kernel** [comment]
I was able to fix this by enabling `esModuleInterop` in my `tsconfig.json`. My project uses `module: "commonjs"`. Hope this is helpful.

**Comment by eXon** [comment]
Let me know if this is not resolved but it looks like it is working as intended.

**Comment by pencilcheck** [comment]
This issue is in v6, if I downgrade to v4 it starts working again.
