### ISSUE TITLE
typescript CookieChangeListener type, should it be 3 params rather than an object?

### ISSUE THREAD

**Issue by stubar** [reactivestack/cookies#212]
I am getting a typescript error...
```Error:(17, 31) TS2345: Argument of type '(cookieName: any, cookieValue: any) => false | void' is not assignable to parameter of type 'CookieChangeListener'.```

based on the documentation for the addChangeListener...
"callback (function): Call that will be called with the first argument containing name, value and options of the changed cookie."
it looks like it should accept 3 params,

but the following type is looking for one options param.

```
export interface CookieChangeOptions {
  name: string;
  value?: any;
  options?: CookieSetOptions;
}

export type CookieChangeListener = (options: CookieChangeOptions) => void;
```

**Comment by eXon** [comment]
The function has only one argument containing the 3 bits of information. I don't see any reason to split them.

**Comment by stubar** [comment]
Sorry to waste your time, you're absolutely right
