### ISSUE TITLE
Parser broke the string value

### ISSUE THREAD

**Issue by npasparuhov** [reactivestack/cookies#215]
Hello, i have a little problem:
Input:
```
import Cookies from 'universal-cookie';

const cookie = new Cookies();
const cookieValue = '"tj_pref_currency:GBP|tj_pref_lang:en|tjcor:en|"';
cookie.set('tj_conf', cookieValue, { path: '/', expires: new Date('2030')});
```

setting the value of a cookie with special characters inside, broke the value for me.

Actual output:
```
%22tj_pref_currency%3AGBP%7Ctj_pref_lang%3Aen%7Ctjcor%3Aen%7C%22
```

Expected output:
```
"tj_pref_currency:BGN|tj_pref_lang:en|tjcor:bg|"
```

**Comment by eXon** [comment]
Is the expected output is from the raw cookie from the browser or when you're trying to read back the cookie using react-cookie?

It is normal to see those weird characters if you're reading `document.cookie`, they need to be encoded. However, if you read the cookie back you should get a clean value.

**Comment by npasparuhov** [comment]
Yeah when i read back the cookie it is decoded and with normal characters, but the problem it that the server do not perform such decode, and accept the cookie into raw format, when i used the plugin it reject my cookie, so i was wondering if there is some way to add new config property 'rawFormat', 'encode' something like this, with which the user can disable the encode and save it in raw format

**Comment by eXon** [comment]
Yes I can probably expose the encoding function. Right now, it is always using `encodeURIComponent`. Be aware that some characters might break the cookie like using `;` because it is the separator between the value and the cookie options.

You might want to consider using `decodeURIComponent` on the value on the backend instead. Is it something possible?
