### ISSUE TITLE
I don't see the need for the CookieProvider in the client.js in the demo package and the readme did not explain why it is or is not needed. 

### ISSUE THREAD

**Issue by haoyitedaniu** [reactivestack/cookies#218]
I tried to remove the CookiesProvider in the client.js and it still works,why?

**Comment by eXon** [comment]
It would work on the client because there is a default one. However, if you're doing server-side rendering, you need the provider so that you can specify the cookies of the client. If you're not doing SSR, you don't absolutely need it.

**Comment by maciekmp** [comment]
Good explanation but examples show it in a different way. Maybe it is a good idea to add information about it?

**Comment by jsphstls** [comment]
I think I see different behaviour with `removeCookie` depending on whether `CookiesProvider` is used or not.

The fact that `CookiesProvider` is optional is not clear in the documentation. It could always be required and if it is not used then an error is thrown when trying to use the hooks.
