### ISSUE TITLE
Cookie Not Stored Under File Protocol

### ISSUE THREAD

**Issue by gorvinsky** [reactivestack/cookies#220]
I am building a mobile app that access some local HTML files which require user to login before doing anything else. User can login fine but when the app is closed and reopened, user have to relogin again because the cookie is not set under "file://" in the last session.

Is there a way to set the cookie under "file://"?

If not, I have an idea to set the cookie under a different domain like "example.com" and then access the cross domain cookie in subsequent session. Is it possible to access cross domain cookie? If yes, how?

**Comment by eXon** [comment]
Using cookies on `file:///` is not reliable. If you're building a mobile app, it would probably be better to use the localStorage instead. Otherwise, cross-domain cookies are a pain and probably don't want to deal with that unless you have no other option.
