### ISSUE TITLE
universal-cookie can't set cookies on the server side

### ISSUE THREAD

**Issue by SilentImp** [reactivestack/cookies#221]
Hi, 
as far as I understand from the code, _universal-cookie_ can't set cookies on the server-side.
Maybe it's a nice idea to have an option to pass a request or set method to the constructor to use it on the server side?
Or I have got it all wrong and I can set cookie server side with this package?

**Comment by eXon** [comment]
Yes it is possible! Most people do it with react-cookie / universal-cookie-express, but you can totally build your own implementation if you have special needs.

Here is an example: https://github.com/reactivestack/cookies/blob/master/packages/universal-cookie-express/src/index.ts

**Comment by eXon** [comment]
Basically, the change listener will be call any time your `universal-cookie` instance set or delete a cookie. Then, you can call the appropriate thing to set the cookies using whatever server library you want.
