### ISSUE TITLE
Can library detect external change to the cookies and trigger re-render?

### ISSUE THREAD

**Issue by chachora** [reactivestack/cookies#223]
For e.g. can react-cookie trigger component re-render if the user clears the cookies in the browser?

**Comment by seanharr11** [comment]
Further, when setting cookies on the server, will `useCookies()` pick up this change and issue a re-render? All signs point to "no". Right now I need to run `setCookie('useless-cookie', 'foobar')` to "nudge" the library to find the new cookie.

**Comment by eXon** [comment]
Cookies change detection could be a nice feature addition. This should definitively be explored. I'll try to squeeze it in the next release.

**Comment by eXon** [comment]
> Further, when setting cookies on the server, will `useCookies()` pick up this change and issue a re-render? All signs point to "no". Right now I need to run `setCookie('useless-cookie', 'foobar')` to "nudge" the library to find the new cookie.

This look like another issue to me. Can you open another issue with more details? What are you running on the server? Is it for SSR?

**Comment by SilentImp** [comment]
face the same problem.
to check the changes considering

- [onvisibilitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/onvisibilitychange) 
- [Broadcast_Channel_API](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) 
- timer + [requestIdleCallback](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback)

**Comment by aej11a** [comment]
@eXon Have you been able to work on change detection? Need this for a project I'm working on, might be able to look into it if you haven't done any work on this yet.

**Comment by erbaker** [comment]
I would immediately use change-detection for cookies 👍 

I found a native implementation here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged

But of course no Edge support.

**Comment by eXon** [comment]
This is still on my icebox because I don't have much time to add new features. If you want to do a PR I would be more than happy to review your code. Otherwise I don't know when this will be done.

**Comment by deepal** [comment]
I think this would be an essential feature. I encountered this when tried to implement a shopping cart using react-cookie. When a user adds an item to the cart in one tab, the other tab is not aware of it because the cookie change in the previous tab is not rendered in the 2nd tab. I'm happy to explore how to do this in a performant way and if I find a way I'll raise a PR.

**Comment by Bosch-Eli-Black** [comment]
MDN says that cookies.onChanged isn't supported on Safari (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged). I suppose that could probably be worked around with a timer.

**Comment by Bosch-Eli-Black** [comment]
Ah, actually, it looks like `cookies.onChanged` is only available in browser extensions, not in normal JavaScript code, so that approach probably won't work at all!

**Comment by jacob-israel-turner** [comment]
@eXon Would you still be open to a PR for this? I have a couple of ideas that I think could work.

**Comment by jacob-israel-turner** [comment]
After some digging, I found a workaround to allow consumers to imperatively refresh the cookie store.

Calling `Cookies.set` causes the store to re-check all cookies. So doing something like this should allow you to cause a refresh:

```
export function refreshCookieStore() {
  CookieStore.set(
    'COOKIE_STORE_RESET',
    `This value is set only for change detection purposes. Do not consume. ${Math.random()}`
  );
}
```

I don't _think_ the `Math.random()` is actually necessary, but I didn't want this function to break if change detection in the future relies on the contents of the cookies.

I'm using the `useCookies` API. This does require you to manually instantiate a `Cookies` instance and pass it into `<CookiesProvider />`. But you can pass that instance instance (or a method like the one I shared above) around to other parts of the application to refresh when needed. In my case, I use the method in a legacy part of my application dealing with login, logout, and other auth state logic.
