### ISSUE TITLE
LICENSE FILE

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [reactivestack/cookies#224]
Hello,

First off, thanks for sharing this project :)

I know that the project already says that the code is MIT licensed, but could you please also add a LICENSE file containing the text of the MIT license?

My understanding is that this may be necessary in order for the code to be considered legally licensed under MIT.

Babel recently went through something similar: babel/babel#7308

**Comment by eXon** [comment]
Yea, it looks like it need to be published with the NPM package. I'll add that.

**Comment by Bosch-Eli-Black** [comment]
Awesome! Thank you! :)

**Comment by eXon** [comment]
It's published now on `v4.0.1`!
