### ISSUE TITLE
Cannot use React in sandboxed iframe without allow-same-origin

### ISSUE THREAD

**Issue by Endeer** [reactivestack/cookies#226]
Hello,

<iframe sandbox="allow-scripts" src="https://my.react.app/"></iframe>

This will crash in Firefox, the application will not render at all. In module universal-cookie called during React initialization, in function hasDocumentCookie() an exception is thrown when trying to access typeof(document.cookie). Console logs DOMException: The operation is insecure.

It should be wrapped in try/catch and return false in case of an error.

Best Regards,
Ender

**Comment by eXon** [comment]
It's a new edge case I was not aware of. When in a sandbox without cookies access, the cookies should be stored in-memory without crashing. I'll take a look.

**Comment by eXon** [comment]
Unfortunately, I've tried a few ways and neither try/catch or putting it in a promise allow to catch the error. As soon as we try to access document, it crashes and cannot be recover. We'll need to dig a little deeper to understand why and what we can do about it.

**Comment by Endeer** [comment]
Interesting. try/catch works for me, I changed the hasDocumentCookie() function from

function hasDocumentCookie() { return (...); }

to

function hasDocumentCookie() { try { return (...); } catch(e) { return false; } }

and it works for me now.

**Comment by eXon** [comment]
In which browser? I've only tried Chrome so far.

**Comment by Endeer** [comment]
Both Firefox and Chrome. http://ejha.cz/wg.html

**Comment by eXon** [comment]
Should work with the last version
