### ISSUE TITLE
secure & httpOnly options not working in universal-cookies

### ISSUE THREAD

**Issue by md18-public** [reactivestack/cookies#233]
I tried to create cookies using 3 options but it's not working.

import Cookies from "universal-cookie";
const cookies = new Cookies(); // Create cookie object.

cookies.set("rem", "31", { path: "/", secure: true, httpOnly: true });

**Comment by eXon** [comment]
You cannot create an httpOnly cookie unless you are running your code into the server. See https://www.owasp.org/index.php/HttpOnly for more detail.

**Comment by bennettstuart** [comment]
I've got a similar issue,

I'm trying to set cookies with `secure: true` using 'react-cookie' and the cookie is just not being set. If I try to set a cookie without the secure property, it set's as expected

**Comment by bennettstuart** [comment]
> I've got a similar issue,
> 
> I'm trying to set cookies with `secure: true` using 'react-cookie' and the cookie is just not being set. If I try to set a cookie without the secure property, it set's as expected

My "secure" cookies weren't being set because I was testing on localhost.
After testing with `ngrok` on `https://`, the secure cookies were set as expected as explained [here](https://github.com/reactivestack/cookies/issues/63#issuecomment-351555260)
