### ISSUE TITLE
How to get cookies as a string?

### ISSUE THREAD

**Issue by borekb** [reactivestack/cookies#235]
What is the inverse of parsing cookies from a string?

```ts
// parsing from a string:
const cookies = new Cookies(req.headers.cookie);

// serializing to a string:
cookies.???
```

`getAll` seems to [return an object](https://github.com/reactivestack/cookies/blob/de3b2ce6d7c2a1897e2c643fadbf4271e6c92d31/packages/universal-cookie/src/Cookies.ts#L53-L62).

**Comment by Dan-Wood** [comment]
`JSON.stringify(cookies)`
`{"name":"value","cookie":"monster"}`

Not sure why you'd want to do that?

Or just for fun, change the output

`Object.keys(obj).map( (key, value) => `${key}=${value}`).join('')`
`name=0cookie=1`

**Comment by borekb** [comment]
Actually I forgot where exactly we needed that – we're using `universal-cookie` in a Next.js app so maybe serializing for later hydration? I'm not totally sure right now.

The point was to get a string that will be parseable via `new Cookie(THAT_STRING)` again. Will `JSON.strinfigy` produce that? Will there be issues with "special characters" like `&`?

**Comment by eXon** [comment]
You don't need to manage all that. You just need to plug [universal-cookie-express](https://www.npmjs.com/package/universal-cookie-express) with Next.js and it will take care of everything for you (sending the cookies to the browser when they are set on the server, reading cookies, etc.)

**Comment by eric-burel** [comment]
You don't have an express server in Next so I don't see how you would do that directly
