### ISSUE TITLE
Jest testing, setting and reading back values

### ISSUE THREAD

**Issue by codelizrd** [reactivestack/cookies#236]
Hi,

I added _react-cookies_ to my project (CRA, TypeScript, Jest), and use the '`useCookies`' hook to read/set cookies and let components re-render upon changes.

In Jest, cookies are updated accordingly when I `mount` a component-tree and trigger actions (I inspected this using the debugger, and `console.log`-ing). 

But I want to start the Jest test with a predefined cookie values; I tried various approaches, but didn't get any to work:

- Using `<CookieProvider cookies={ownCookiesInstance} />` as a wrapper in my test; it seems that the CookieProvider is ignored - as the library detects its not running in a browser; a CookieProvider is not required to use useCookies in a Component (am I right about this?).

- Trying to spyOn `useCookies`: 
```
import * as reactCookie from 'react-cookie';
jest.spyOn(reactCookie, 'useCookies');
```
results in `TypeError: Cannot set property useCookies of #<Object> which has only a getter` so I cannot inspect/test useCookies calls. 

- Trying to mock `useCookies`:
```
jest.mock('react-cookie', () => ({
    useCookies: () => { console.log('test - the mock is used!'); }
}));
```
It seems this mock is not used inside my Functional Components.

1. What is the best way to set a cookie at the beginning of a (Jest) test
2. What is the best way to inspect a cookie value during a (Jest) test?

**Comment by dragon-slayer** [comment]
Adding on to this - I tried setting cookies according to [this stackoverflow](https://stackoverflow.com/questions/50761393/how-to-mock-cookie-getlanguage-in-jest), namely:

```
Object.defineProperty(window.document, 'cookie', {
            writable: true,
            value: 'myCookie=omnomnom',
        });
```

Also tried the browser api directly:
`document.cookie = "name=value"`

Neither of them are 'picked up' by react-cookie during Jest testing.

**Comment by eXon** [comment]
Fixed with `v4.0.3`

**Comment by phalt** [comment]
A fix was made, but which solution is now the working solution? I'm also trying to write tests and set up default cookie state.

**Comment by mrooding** [comment]
@phalt there's an example on how to do this in the source code: https://github.com/reactivestack/cookies/blob/master/packages/react-cookie/src/__tests__/useCookies-test.js

**Comment by bhattibytes** [comment]
This works at the top of a test suite as the default cookie state.  
```
const mockCookie = jest.fn();
  jest.mock('react-cookie', () => ({
    useCookies: () => [mockCookie, mockCookie],
  }));
```

**Comment by domnantas** [comment]
https://github.com/bendotcodes/cookies/blob/main/packages/react-cookie/src/__tests__/useCookies-test.js does not mock `useCookies`, so it's not a great example.

```js
mockSetCookie = jest.fn();
mockRemoveCookie = jest.fn();

jest.mock('react-cookie', () => ({
    useCookies: () => [{ cookie1: 'value1' }, mockSetCookie, mockRemoveCookie],
}));
```
does not seem to work:
```js
const [cookies] = useCookies();
// cookies is still  {} here
```

I have also tried
```js
import * as reactCookie from 'react-cookie';

jest.spyOn(reactCookie, 'useCookies').mockReturnValue([cookies, setCookie, removeCookie]);
```

but I'm getting an error `Cannot redefine property: useCookies`
