### ISSUE TITLE
How to delete the cookie I want to delete ?

### ISSUE THREAD

**Issue by Vang-z** [reactivestack/cookies#238]
Pls forgive me, I'm not a navicate English Speaker. When I try to delete the cookie, but no use.
I create a cookie just like this.
`cookies.set(
        "_lc",
        "lcCookie",
        {path: "/", maxAge: 604800}
      );`
but when I try to delete it
`cookies.remove({name: '_lc'});`
the code doesn't work.... Pls help me

**Comment by monmush** [comment]
Having the same issue. Can't delete the cookies using cookies.remove

**Comment by Vang-z** [comment]
> 有同样的问题。无法使用cookies.remove删除cookie

I try to set a new cookie to cover it, It work. the code just like that you can see it.`cookies.set( "_lc", "", {path: "/", maxAge:  0} );` to

**Comment by eXon** [comment]
@Vang-z To remove a cookie you have to make sure to include the same path and domain. This should work:

`cookies.remove( "_lc", {path: "/" );`

**Comment by dominiceden** [comment]
Yes, you have to include the path and domain like so:

```
cookies.remove('cookie_name', {
      path: '/',
      domain: window.location.hostname,
    });
```
