### ISSUE TITLE
Improve tree-shaking

### ISSUE THREAD

**Issue by kinday** [reactivestack/cookies#241]
Hi there,

I’ve had a quick glance at code and could make a PR, but feels better to ask maintainers first.

There is non-standard (yet widely supported) [`sideEffect` field](https://github.com/stereobooster/package.json#sideeffects) which, if present in `package.json`, allows build tools ([example from Webpack docs](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free)) to better handle tree-shaking.

So, the code (at least of `universal-cookie` package) seems to be side effect free, but I’d like to get confirmation from you. If you haven’t ever dealt with `sideEffects` field, in this case we speak about side effects on module evaluation (i.e. import or `require`).

I tried to cover essential parts, but if further clarification is needed, feel free to ask me.

**Comment by eXon** [comment]
Yes I'm sure we can add this. Good idea!

**Comment by eXon** [comment]
Done with `v4.0.3`
