### ISSUE TITLE
Uppercase cookie name refresh bug

### ISSUE THREAD

**Issue by robcochranff** [reactivestack/cookies#242]
Hi,

It seems when I set a cookie name to uppercase, my example was like

'COOKIE_NAME'

Then if I logged out of my app and back in again, React wouldn't see it until I refreshed the page.  I tried lowercasing it 'cookie_name' and it worked

Riddle me this..

**Comment by eXon** [comment]
Cookie names are case-sensitive but they do work with any casing. Do you have a more detailed steps to reproduce?
