### ISSUE TITLE
What happens when there are multiple cookies of the same name? (universal-cookie)

### ISSUE THREAD

**Issue by marioliu** [reactivestack/cookies#243]
Say there are two cookies stored for a domain.

1. Name `"cookie"` with value `"parent"` on domain `parent.com`
2. Name `"cookie"` with value `"child"` on domain `child.parent.com`

When using `cookies.get("cookie")` on `child.parent.com`, which value does the function return? Is there a default option, or is it selected based on the current domain?

**Comment by eXon** [comment]
The browser will use the child value first and if you're anywhere child.parent.com else the cookie value would be parent.
