### ISSUE TITLE
Would be good to include an example for use with redux

### ISSUE THREAD

**Issue by zihaom** [reactivestack/cookies#247]

**Comment by eXon** [comment]
There is nothing special for Redux. Not sure it is necessary, do you see any challenges that are worth mentioning?

**Comment by zihaom** [comment]
I am getting the cookies.getAll is not a function error

**Comment by eXon** [comment]
Would you mind sharing a steps to reproduce?

**Comment by zihaom** [comment]
Main.js:
import React, { Component, PropTypes } from 'react';
import {Form,Alert,Badge,Modal,Navbar,Nav,NavDropdown,FormControl,Jumbotron,InputGroup,Popover, Button,Container} from 'react-bootstrap';
import { withCookies } from 'react-cookie';
import { withRouter,Switch,useRouteMatch,Route } from "react-router-dom";
import { LinkContainer } from 'react-router-bootstrap';
import axios from 'axios';

import Account from './account';
import Mygoods from './mygoods';
import Mylist from './mylist';
import Postnew from './postnew';
import Advsearch from './advsearch';
import Search from './search';
import View from './view';
import Edit from './edit';

const url = "http://ec2-18-221-135-84.us-east-2.compute.amazonaws.com:3456/";

class Welcome extends Component {
    render() {
      return (
          <Jumbotron>
              <h1>Hi, Welcome to Barter.</h1>
              <p>  On Barter, you can post your used stuff for other users or check out some used goods. 
                  Buying used goods is not only cheap, but also environmentlly friendly. 
                  Barter only post your contact information, and where you trade, how you trade is completely
                  up to you!</p>
          </Jumbotron>
      );
  }
}

class Main extends Component {
    constructor(props, context) {
        super(props, context);
    }
    handleLogout(event) {
        event.preventDefault();
        console.log(this.props);
        const p = this.props;
        axios.get(url+"logout",{})
            .then(res=>{
                console.log(res.data);
                if(res.data.status === 0){
                    p.cookies.set('token', "", { path: '/' });
                    p.cookies.set('email', "", { path: '/' });
                    p.Logout();
                    p.history.push('/');
                }else{
                    console.log(res.data.status);
                    p.err(res.data.status);
                }
            });
    }
    handleSearch(event) {
        event.preventDefault();
        const name = event.target.search.value.trim();
        this.props.history.push('/main/search?name='+name);
    }
    render() {
            let { path, localurl } = useRouteMatch();
            const back ={backgroundColor: 'rgba(255,215,0,0.7)', position: 'absolute', left: '50%', top: '20%',transform: 'translate(-50%, -50%)'};
            console.log(this.props.cookies.get("token"));
            return (
                <div>
                <Navbar collapseOnSelect expand="lg" bg="light" variant="warning">
                <LinkContainer to="/main">
                <Navbar.Brand >BARTER</Navbar.Brand>
                </LinkContainer>
                <Navbar.Toggle aria-controls="responsive-navbar-nav" />
                <Navbar.Collapse id="responsive-navbar-nav">
                    <Nav className="mr-auto">
                    {this.props.cookies.get("token") !== ""?
                        <div><NavDropdown title={"Hi,"+this.props.firstname} id="collasible-nav-dropdown">
                            <NavDropdown.Item onClick={this.handleLogout().bind(this)}>logout</NavDropdown.Item>
                            <NavDropdown.Divider />
                            <LinkContainer to={`${path}/account`}><NavDropdown.Item >Account</NavDropdown.Item></LinkContainer>
                            <LinkContainer to={`${path}/mygoods`}><NavDropdown.Item >My goods</NavDropdown.Item></LinkContainer>
                            <LinkContainer to={`${path}/mylist`}><NavDropdown.Item >My list</NavDropdown.Item></LinkContainer>
                        </NavDropdown>
                        <LinkContainer to={`${path}/postnew`}><Nav.Link >Post a good</Nav.Link></LinkContainer></div>
                        :<div><LinkContainer to="/login">
                            <Nav.Link >Log in</Nav.Link></LinkContainer></div>
                    }                 
                    </Nav>
                    <Nav>
                    <LinkContainer to={`${path}/advsearch`}><Nav.Link >Advanced search</Nav.Link></LinkContainer>
                        <Form inline  onSubmit={this.handleSearch.bind(this)}>
                            <FormControl type="text" name="search" placeholder="Search goods..." className="mr-sm-2" />
                            <Button variant="outline-warning">Search</Button>
                        </Form>
                    </Nav>
                </Navbar.Collapse>
                </Navbar>
                <Container style={back}>
                <Switch>
                    <Route exact path={path} render={() => (<Welcome/>)}/>
                    <Route exact path={`${path}/account`} render={() => (<Account />)}/>
                    <Route exact path={`${path}/mygoods`} render={() => (<Mygoods />)}/>
                    <Route exact path={`${path}/mylist`} render={() => (<Mylist />)}/>
                    <Route exact path={`${path}/postnew`} render={() => (<Postnew />)}/>
                    <Route exact path={`${path}/advsearch`} render={() => (<Advsearch/>)}/>
                    <Route path={`${path}/search`} render={() => (<Search/>)}/>
                    <Route path={`${path}/view`} render={() => (<View err={this.props.err} err_message={this.props.err_message}/>)}/>
                    <Route path={`${path}/edit`} render={() => (<Edit />)}/>
                </Switch>
                </Container>
                </div>
            );
    }
}
export default withCookies(withRouter(Main));


App/js:
import React, { Component } from 'react';
import { Route } from 'react-router-dom';
import {Row,Col,Form,Badge,Modal,Navbar,Nav,NavDropdown,FormControl,OverlayTrigger,InputGroup,Popover, Button,Container} from 'react-bootstrap';
import { LinkContainer } from 'react-router-bootstrap'
import { withCookies } from 'react-cookie';

import Logincontainer from './container_login';
import Signupcontainer from './container_signup';
import Maincontainer from './container_main';

class Index extends Component {
    render() {
      const back ={position: 'absolute', left: '50%', top: '30%',transform: 'translate(-50%, -50%)'};
      return (
          <Container style={back}>
            <Row>
            <Col> </Col>
            <Col>    
                <LinkContainer to="/main">
                    <Button variant="secondary" size="lg">
                        Guest entrance
                    </Button>
                </LinkContainer>
            </Col>
            <Col>
                <LinkContainer to="/login">
                    <Button variant="warning" size="lg">
                        Login
                    </Button>
                </LinkContainer>
            </Col>
            <Col>
                <LinkContainer to="/signup">
                    <Button variant="info" size="lg">
                        Sign up
                    </Button>
                </LinkContainer>
            </Col> 
            </Row>
          </Container>
      );
  }
}

class App extends Component {
    render() {
        return (
            <div>
                <Route path="/" exact render={() => (<Index />)} />
                <Route path="/login" render={() => (<Logincontainer cookies={this.props.cookies}/>)} />
                <Route path="/signup" render={() => (<Signupcontainer/>)}/>
                <Route path="/main" render={() => (<Maincontainer/>)}/>
            </div>
        )
    }
}

export default withCookies(App);


package.json:
{
  "name": "barter",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "axios": "^0.19.0",
    "bcrypt": "^3.0.7",
    "bootstrap": "^4.3.1",
    "cookie-session": "^1.3.3",
    "crypto": "^1.0.1",
    "ejs": "^3.0.1",
    "express-session": "^1.17.0",
    "form-data": "^3.0.0",
    "jquery": "^3.4.1",
    "mongodb": "^3.3.4",
    "nodemailer": "^6.3.1",
    "query-string": "^6.9.0",
    "react": "^16.12.0",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-cookie": "^4.0.1",
    "react-dom": "^16.12.0",
    "react-images-upload": "^1.2.7",
    "react-redux": "^7.1.3",
    "react-router-bootstrap": "^0.25.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.2.0",
    "redux": "^4.0.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {}
}

**Comment by mogafk** [comment]
Example not have getAll calling. Cannot reproduce

**Comment by LauraBeatris** [comment]
@zihaom Can you please provide a readable and reproducible example? Thanks
