### ISSUE TITLE
What is the point of `cleanCookies` function in utils.ts?

### ISSUE THREAD

**Issue by goepi** [reactivestack/cookies#248]
I was looking at the source code at this function in `utils.ts`:

export function cleanCookies() {
  document.cookie.split(';').forEach(function(c) {
    document.cookie = c
      .replace(/^ +/, '')
      .replace(/=.*/, '=;expires=' + new Date().toUTCString() + ';path=/');
  });
}

It's not used anywhere except in a test, `Cookies-test.js`, where it is run in a `beforeEach` block in a Jest `describe` block. Why does that function exist?

**Comment by eXon** [comment]
It is only used within the tests to clean all cookies before performing a new test. It is necessary to make sure something from a test doesn't leak into the next one.

I'm not sure what's the confusion?

**Comment by goepi** [comment]
My bad, ok, I was confused because the tests pass without the `beforeEach`, and I thought document.cookie wasn't being used anywhere, but it is in the Cookies class.
