### ISSUE TITLE
react-cookie cookies.set does not set object 

### ISSUE THREAD

**Issue by BernardA** [reactivestack/cookies#252]
I've been unable to set an object to cookies using below:

      const profileString = JSON.stringify(userProfile);
      cookies.set('userProfile', profileString, { path: '/' });

It works for plain strings, and reading your docs I understood it should work by stringifying the object. 

Are there any limits concerning depth of the object?

**Comment by mogafk** [comment]
library not have limit by depth or length serialized object. It's just JSON.stringify at
https://github.com/reactivestack/cookies/blob/v4.0.3/packages/universal-cookie/src/Cookies.ts#L73
and JSON.parse at
https://github.com/reactivestack/cookies/blob/v4.0.3/packages/universal-cookie/src/utils.ts#L44
also https://www.npmjs.com/package/cookie(dependency) does not restrict cookie length

but different browser have different restriction for cookies
In my Google Crome 79.0.3945.79 max cookie size is 4096 bytes, you can check it on http://browsercookielimits.squawky.net/

try for yourself something like:
```
document.cookie = `example_1=${'example_value_1'.repeat(10)}`
console.log(document.cookie.indexOf('example_1') !== -1 ? 'successfully set' : 'failed set')
// in my main browser it prints "successfully set"
document.cookie = `example_2=${'example_value_2'.repeat(10000)}`
console.log(document.cookie.indexOf('example_2') !== -1 ? 'successfully set' : 'failed set')
// in my main browser it prints "failed set"
```

**Comment by BernardA** [comment]
Thanks @mogafk. I tried with a plain object and it worked. So the issue seems to be that the object I intended to save in cookies is too big. I will save it in indexeddb instead.
