### ISSUE TITLE
cookie path not getting saved

### ISSUE THREAD

**Issue by ClaraGaya** [reactivestack/cookies#253]
Having explicity set up the path as '/' when setting the cookie
`cookies.set(name, value, {  path: '/', expires: expires });`

when going to mysite.com/page/ 
then accepting cookies
checking in the browser the cookie path is '/page/' instead of '/'

**Comment by mogafk** [comment]
can you provide additional step to reproduce? I tried but in my enviroment it fine

**Comment by Billy-** [comment]
I also encounter this sometimes. Hard to track down / reproduce what's causing it, but every now and then my app stops working as expected and the culprit is always a cookie with the path set to where the page was loaded, despite my options being hard-coded to use `'/'` as a path.

**Comment by eXon** [comment]
Without a way to reproduce it would be hard to solve. Let me know if there is a way.
