### ISSUE TITLE
Setting a cookie as SameSite=None is not working

### ISSUE THREAD

**Issue by kevinblanco** [reactivestack/cookies#254]
If I set a cookie as `sameSite=none` it trows : `TypeError: option sameSite is invalid` 

**Versions:** 
universal-cookie@4.0.3 
react@16.9.0

### Example: 
`
cookies.set('sso_init', 1, { path: '/', sameSite: 'none', secure: true });`

**Comment by christophersjchow** [comment]
This is affecting us with `react-cookie` as react-cookie has a loose version for dependency here: https://github.com/reactivestack/cookies/blob/master/packages/react-cookie/package.json#L41

A work around is to use `resolutions` in `package.json` to force the use of 4.0.3 where `CookeSetOptions` has been updated.

```
resolutions: {
  'universal-cookie': '4.0.3'
}
```
