### ISSUE TITLE
Browsers compatibility for 'react-cookies'

### ISSUE THREAD

**Issue by cbdeveloper** [reactivestack/cookies#255]
Excuse my ignorance, but from the image below: does it mean that this package will not work on browsers releases before those versions? 

I guess that this is not the case, so what does those browser versions mean?

And what is the browser compatibility? How can I know that?

Thanks

![image](https://user-images.githubusercontent.com/43407798/73590363-7cc37e00-44d9-11ea-8448-3f8539c1e3ea.png)

**Comment by Axxxx0n** [comment]
I want to know the same. fyi IE 11 is not supported because you dont polyfill promises

**Comment by eXon** [comment]
No, it only teels which version it has been tested on.
