### ISSUE TITLE
setCookies with path not working in EDGE

### ISSUE THREAD

**Issue by riorinald** [reactivestack/cookies#257]
hello, i tried to use setCookies function with option 

> { path:'abcd', expires: expiredTime }

the option that i used only expires  and path, and i developin on localhost 
this path working in chrome. so i get path:'abcd' 
but in EDGE or IE the cookies is not exist.

when the path option is only '/' its working fine in IE/EDGE.

**Comment by eXon** [comment]
Just cleaning up old bugs, let me know if it's still an issue.
