### ISSUE TITLE
Add get and remove with regex

### ISSUE THREAD

**Issue by muuvmuuv** [reactivestack/cookies#259]
It would be great if I could get cookies based on a regex string and also remove them with regex. So I could easily delete cookies for Google Analytics for example.

**Comment by gkalil** [comment]
I like this idea too. I can work on a PR for this feature. @eXon do you think it will be relevant?

**Comment by eXon** [comment]
I'm not sure I want to add an extra feature specifically for that. You could easily get all the cookies and remove only the one matching the regex. If there is a need for that maybe I will reconsider but I don't think it is at the moment.
