### ISSUE TITLE
react-cookie useCookies does not refresh in parents

### ISSUE THREAD

**Issue by generalpiston** [reactivestack/cookies#260]
## Description

The `useCookies` hook appears to be stateful rather than updating the global context. Is that intentional?

## Example

```
// This function component never updates
function Parent() {
  const [cookies, setCookie, removeCookie] = useCookies(['test']);

  if (cookie.test === 'test') {
    return <Child2 />;
  } else {
    return <Child />;
  }
}

function Child() {
  const [cookies, setCookie, removeCookie] = useCookies(['test']);

  useEffect(() => {
    setCookie('test', 'test', { path: '/' });
  });

  return null;
}

```

**Comment by na2axl** [comment]
Hi all, @eXon or anyone in the @reactivestack please do you have a workaround for that ? It's strange that updating cookies only affect the current component instead of the global context...

**Comment by dennismorello** [comment]
We'd better fix this by ourselves

**Comment by generalpiston** [comment]
@eXon know any thing about the above?

**Comment by jazeee** [comment]
I observe this issue in my app.
I did some testing, and concluded that I only need the underlying `universal-cookie` package.
I wrote the following alternative provider (simpler and less functionality, but does the job):
```
import { useEffect, useState } from 'react';

import constate from 'constate';
import Cookies from 'universal-cookie';

const globalCookies = new Cookies();

const setGlobalCookie = globalCookies.set.bind(globalCookies);
const removeGlobalCookie = globalCookies.remove.bind(globalCookies);

function useCookies() {
  const [cookies, setCookies] = useState(globalCookies.getAll());

  useEffect(() => {
    function onChange() {
      const newCookies = globalCookies.getAll();
      setCookies(newCookies);
    }
    globalCookies.addChangeListener(onChange);
    return () => {
      globalCookies.removeChangeListener(onChange);
    };
  }, []);

  return {
    setCookie: setGlobalCookie,
    removeCookie: removeGlobalCookie,
    cookies,
  };
}

export const [CookiesProvider, useCookiesContext] = constate(useCookies);
```

**Comment by jazeee** [comment]
Actually, now that I look at it more, I believe the issue should be fixed by using `useLayoutEffect`
This ensures that the hook calls `addChangeListener` before other code runs.
https://kentcdodds.com/blog/useeffect-vs-uselayouteffect#one-special-case

I changed my solution above to `useLayoutEffect` which resolved the one issue I had - that cookie listener was not in place on initial page load.

**Comment by pavankjadda** [comment]
Waiting for PR #288 to be merged.

**Comment by tgreco** [comment]
Please get this merged!

**Comment by pavankjadda** [comment]
Thanks. But I created my own library cookies management since I didn't know when PR was going to merge. 

https://github.com/ngxsmart/react-cookie-service
