### ISSUE TITLE
Using mixed imports brakes when using native ESmodules.

### ISSUE THREAD

**Issue by chmelevskij** [reactivestack/cookies#262]
https://github.com/reactivestack/cookies/blob/a97969a9755f2a7fc5977a448a97f0fd39ac3a3c/packages/universal-cookie/src/Cookies.ts#L14

When trying to consume this package with rollup and `<script type="module" />` having mixed imports means that `require` is not defined.

**Comment by chmelevskij** [comment]
One of the solutions would be to remove object assign instead of spreading https://github.com/reactivestack/cookies/pull/263

This does add the helper into the TS output though.

**Comment by niltonvasques** [comment]
I'm facing the same issue here, when I tried to use react-cookie package with snowpack.

![image](https://user-images.githubusercontent.com/2291529/83344497-2aa33580-a2de-11ea-938a-298b0d4b6c63.png)

https://www.pika.dev/npm/snowpack/discuss/271#comment-6902

**Comment by shox-harri** [comment]
Same issue

**Comment by shox-harri** [comment]
This Rollup plugin as temporary fix 
```
function fixObjectAssign () {
    return {
        name: 'fix-object-assign',
        transform ( code, id ) {
            if (id.indexOf('universal-cookie/') > - 1) {
                return code.replace("require('object-assign')", 'Object.assign');
            }
            return null;
        }
    };
}

...
plugins: [
                ...
                multiEntry(),
                ...
```

 Please make that you have Object.assign polyfill https://caniuse.com/?search=Object.assign

**Comment by itaysmalia** [comment]
> I'm facing the same issue here, when I tried to use react-cookie package with snowpack.
> 
> ![image](https://user-images.githubusercontent.com/2291529/83344497-2aa33580-a2de-11ea-938a-298b0d4b6c63.png)
> 
> https://www.pika.dev/npm/snowpack/discuss/271#comment-6902

any update on this one? I am using snowpack too.

**Comment by chmelevskij** [comment]
@itaysmalia which version are you using?

**Comment by itaysmalia** [comment]
@chmelevskij 
```json
"snowpack": "^3.0.1",
"react-cookie": "^4.0.3",
````

**Comment by jaredh159** [comment]
Also having the issue @itaysmalia described, `react-cookie` + `snowpack`.  The line that seems to be killing me is:

https://github.com/reactivestack/cookies/blob/master/packages/react-cookie/src/withCookies.tsx#L8

**Comment by chmelevskij** [comment]
For people still having the issue, you can use https://www.npmjs.com/package/patch-package till this gets resolved to fix the issue.

**Comment by Gideon-Felt** [comment]
Found this:
https://www.npmjs.com/package/react-cookie-esm-fix

**Comment by eXon** [comment]
This is fixed in the last release
