### ISSUE TITLE
Why/When would one need this lib?

### ISSUE THREAD

**Issue by oskarleonard** [reactivestack/cookies#265]
Has i understood it correct in that one only needs this lib if i want other components to subscribe to cookie changes?

But in In the "Simple example" code it is not used like that, there we now have 2 different states for the same thing (cookie and react state), isnt that redundant? Why not just use the cookie state for displaying that data instatead of introducing react state? 
```
const { cookie } = this.props;
const name = cookie.get('name') || 'Ben'; // Or set Ben as default cookie name in the constructor. for same result
// So if one updated that cookie from another component this component will re render
```

Many examples out there but a lot do not say why and when you need it, just that you should use it.

I keep most of my internal state in Redux and external state (state needed to handle a page refresh) in the URL.

Would be great with a documentation for its use case.

**Comment by morficus** [comment]
@oskarleonard cookies are not only intended for storing state. You can store any set of arbitrary data in a cookie and have it persist between user sessions or for a fixed amount of time.

Cookies are typically used to store data that needs to be transmitted on every request (like a secure token for example). Cookies can also be set server-side but read client-side (depending on the cookie settings). So this lib can be used any time you want to deal with cookies (either client-side or server-side). Cookies are not specific to state in react.

If you do not have a case for using cookies, then you probably do not have a case for any of these libs.

One bit of information you might not be aware of... is that this repo holds more than just the react-cookies project. Take a look at the "packages" directory: https://github.com/reactivestack/cookies/tree/master/packages

**Comment by oskarleonard** [comment]
@morficus Thanks for your explanation. I know what cookies are and when they are used. I have developed several SSR react sites (with login and accessTokens involves). However i still struggle to understand why this lib is needed or when to use it instead of just setting and getting cookies the "normal" javascript way.

As i pointed out in the OP, from my understanding, **this lib is just needed if we need our components to re-render when changing a cookie value?**. But nothing in the documentation say this. 

Take accessToken cookie for example, on logout, the pattern is:
1. clean Redux store
2. remove `removeCookie('accessToken')`
3. redirect to /login

```
// With normal Javascript way i mean the below
export function removeCookie(cname) {
  const expires = `expires=Thu, 01 Jan 1970 00:00:00 GMT`;
  document.cookie = `${cname}=;${
    window.location.host !== `localhost:${process.env.APP_PORT}`
      ? ';secure'
      : ''
  };${expires};path=/`;
}
```

Okay, since `window` nor `document` exists on the server, **this lib would also help if you need to SSR a cookie value on first render**. For example: 
```
class SomeComponent extends PureComponent {
  render() {
    const { cookies } = this.props;
    return (
      <article>
            <h1 className={styleHelper.text1}>{cookies.get('accessToken')}</h1>
      </article>
    );
  }
}
```

**Comment by morficus** [comment]
> this lib is just needed if we need our components to re-render when changing a cookie value?.

there is more than just 1 thing in "this lib". if you are talking about `react-cookie` specifically.. that is just a wrapper around the base `universal-cookie` library ([see list of libs here](https://github.com/reactivestack/cookies/tree/master/packages)). So the use  cases go well beyond just React applications.

my use case for using this lib is as a utility (specifically `universal-cookie`) to deal with cookies when writing isomorphic functions. I don't even write anything using React 🤷

**Comment by eXon** [comment]
I wouldn't call setting and getting cookies on document.cookies a convenient way. Personally I think the API is aweful. It's here to provide an easier API to use the cookies within JavaScript as well as React. It also provide a nice way to support cookies when doing SSR with React and provide an easy integration with some Node.js routers.
