### ISSUE TITLE
Removing cookies missing the '.' prefix

### ISSUE THREAD

**Issue by deleemillie** [reactivestack/cookies#267]
Perhaps I am misunderstanding what need to happen, if so please let me know.

Ultimately, my website is running under the url:
`https://randomstring.cloudfront.net/` 

Another service sets a cookie with the domain `randomstring.cloudfront.net`. My website which runs under `randomstring.cloudfront.net` directly, needs to be able to delete this cookie.

This works fine when the domain set in the cookie is `.randomstring.cloudfront.net`. But _not_ when the domain of the cookie is `randomstring.cloudfront.net` (effectively, without the '.' prefix).

Using this library, the code below sets a cookie with the domain value `.randomstring.cloudfront.net`, despite the fact that the domain below is specified to not include that full stop prefix.

```
cookies.set('test', 'test', {
    domain: 'randomstring.cloudfront.net',
    path: '/',
});
```

Deleting the cookie with those same options (again, without the explicitly specified full stop prefix), deletes this cookie fine (despite the fact that I am _not_ including the full stop prefix in the options, but the set cookie _does_ include that prefix).

The same code won't delete the cookie if that same cookie does not explicitly have that full stop prefix in the domain.

I am confused, because the documentation both for setting and removing the cookie has:
```
domain (string): domain for the cookie (sub.domain.com or .allsubdomains.com)
```

Should I then not be able to specify which I want? I tried changing the various settings related to `sameSite`, but it didn't seem to have any effect. The code works fine so long as the cookie set includes that full stop prefix (irrespective of whether the cookie is set locally or externally).

**Comment by eXon** [comment]
Just cleaning up old bugs, let me know if it's still an issue.
