### ISSUE TITLE
Expiry not working

### ISSUE THREAD

**Issue by gear4s** [reactivestack/cookies#268]
when I do:

```js
      setCookie("authtoken", "myToken", {
        path: "/",
        expires: new Date(new Date().getTime() + (30*24*60*60*1000))
      });
```

the token is saved, but not for 30 days. console.log shows that the date is a date object 30 days from today.

**Comment by montaserfzy** [comment]
this issue still not solved

**Comment by fannyhasbi** [comment]
Same problem with me

**Comment by mas-iota** [comment]
Why did you close this?

**Comment by gear4s** [comment]
this is not an issue. it was misconfiguration of the service. please make sure your configuration is correct.

**Comment by Julienblc** [comment]
Still have this issue, my cookie is stored for only 7 days. Any solution or example ?

**Comment by timyourivh** [comment]
For anyone wondering, a workaround is to use `maxAge` instead:

```diff
cookies.set('key', 'value', {
-  expires: dayjs().add(1, 'year').toDate()
+  maxAge: 31557600, // 1 Year
})
```

`expires` still seems to be broken
