### ISSUE TITLE
Some cookies are misusing the recommended “sameSite“ attribute in Firefox

### ISSUE THREAD

**Issue by rossPatton** [reactivestack/cookies#272]
Browser: Firefox

The Error:
<img width="1432" alt="Screen Shot 2020-06-17 at 11 41 10 AM" src="https://user-images.githubusercontent.com/2379901/84919082-77815d00-b08f-11ea-8d1c-32bc74cbe651.png">

The Cookies:
<img width="1226" alt="Screen Shot 2020-06-17 at 11 41 39 AM" src="https://user-images.githubusercontent.com/2379901/84919131-86680f80-b08f-11ea-8a97-ab2e17df96ca.png">

Same error occurs on prod/live.

So, both of my cookies are set using this library, and both include SameSite and Strict. Why do I get this error? Seems to be pointing to something internal in the library, but no other cookies are being set.

I only get this when I'm running Firefox, Chrome/Safari does not display these errors.

**Comment by simeonpashley** [comment]
I have the same issue and behaviour, the warning is triggered by Facebook cookies but no cookies are stored for any site.
For me, this only happens in a Production build.

**Comment by jota12x** [comment]
I got this warning as well. Is there any explanation for this? I am using a dev build in Chrome.

**Comment by eXon** [comment]
Just cleaning up old bugs, let me know if it's still an issue.
