### ISSUE TITLE
Will this library work on localhost?

### ISSUE THREAD

**Issue by ColdTuna** [reactivestack/cookies#275]
I'm trying to get this working and the cookie is not being accessible from a subdomain.

This is how I set it:

    const [cookies, setCookie] = useCookies(["_token"]);
    setCookie("_token", "newToken", {
      path: "/",
      expires: new Date(2025, 11, 24, 10, 33, 30, 0),
      domain: ".localhost",
      secure: false,
      httpOnly: false,
    });

Then in my subdomain, I check the Dev Console > Storage > Cookies and it is not there. Even when I explicitly set to the subdomain, I don't see it there. Example: `domain : "example.localhost"`. I am using `<CookiesProvider />` wrapping around my app.

Any idea why?

**Comment by eXon** [comment]
Localhost is not a regular domain name, you can't use subdomains. Here is a SO with an easy solution for you :) https://stackoverflow.com/a/19016600

**Comment by ColdTuna** [comment]
Thanks man! You're life saver for clearing this up for me. I spent so many hours trying to get this to work since I can't share the same instance of redux over on a different subdomain.

**Comment by Startouf** [comment]
It would be interesting to add this as a part of the README on "how to test locally"
