### ISSUE TITLE
No server cookies with Cookies class

### ISSUE THREAD

**Issue by quentinxhu** [reactivestack/cookies#277]
Hello, I believe there is an issue with the `Cookies` class when used during server-side rendering. If the following scenario is expected, I think it's worth mentioning in the docs that the `Cookies` class won't return the cookies server-side and only the `useCookies` hook can be used during the server-side render.

### Issue

While the `const [cookies] = useCookies();` is working well both client and server-side and returning the cookies object, when trying to get cookies through the `Cookies().getAll()` class, it only works client-side and returns an empty object server-side.

### Setup

Our application has `react-cookie` setup for server-side rendering in the exact same way as it is detailed in the guide [here](https://github.com/reactivestack/cookies/tree/master/packages/react-cookie#server-rendering-example) using `universal-cookie-express` server-side.

### Example

```ts
import { Cookies } from 'react-cookie';

const cookies = new Cookies();
const allCookies = cookies.getAll();

console.log(allCookies);

// server-side ---> {}
// client-side ---> { ... the actual cookies }
```

**Comment by ardok** [comment]
Based on your code example, I think it works as expected.

If you want to pass the cookies from the server to client, you need to add `CookieProvider` on the server side.

Here's what I did in my project (server side).
```
export function registerReactCookieMiddlewares(app: FusionApp) {
  app.middleware(koaCookiesMiddleware());
  app.middleware((ctx: Context, next: () => Promise<*>) => {
    if (ctx.element) {
      ctx.element = (
        // $FlowFixMe it will be there from koaCookiesMiddleware
        <CookiesProvider cookies={ctx.request.universalCookies}>
          {ctx.element}
        </CookiesProvider>
      );
    }
    return next();
  });
}
```

What's important is to NOT add `CookieProvider` on the client side.
The documentation says to do this:
```
// src/client.js
import React from 'react';
import ReactDOM from 'react-dom';
import { CookiesProvider } from 'react-cookie';

import App from './components/App';

const appEl = document.getElementById('main-app');

ReactDOM.render(
  <CookiesProvider>
    <App />
  </CookiesProvider>,
  appEl
);
```

In my case (using Fusionjs framework, basically koa), I had to not do that in order for the cookies to be synced between server and client.
