### ISSUE TITLE
Better error message for invalid expires field

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [reactivestack/cookies#280]
Hello,

Currently when the user passes an "expire" option that's not a `Date`, they receive the message `option expires is invalid`.

Could you please enhance this error message so that it says something like `"expire" must be a Date object`? I think this would be helpful :)

Thanks.

**Comment by LucasCaixeta** [comment]
Totally agree. I tried passing  `date.toUTCString();` and received that error... the expires is not invalid, the value that is being passed is.

**Comment by bryantobing12** [comment]
how to set expire on this library? i tried to set Date but still the cookies wasn't set

**Comment by eXon** [comment]
You have to use a Date object, it's part of the documentation. Make sure you are using `expires `and not `expire`, which would not work.
