### ISSUE TITLE
Return same datastructure from withCookies and useCookies

### ISSUE THREAD

**Issue by DianaKoenraadt** [reactivestack/cookies#287]
I cannot easily switch between usage of `withCookies` and `useCookies`. Honestly, the `useCookies` typing makes no sense to me at all. Please make both return the same identical datastructures so that my method of reading the data in the cookie (JSON) that used to take `Cookies` type can be handed whatever rolls out of `useCookies`, too.

**Comment by DianaKoenraadt** [comment]
Preferably, return `Cookies` object from `useCookies`. 

```
Argument of type '{ [name: string]: any; }' is not assignable to parameter of type 'Cookies'.
  Type '{ [name: string]: any; }' is missing the following properties from type 'Cookies': cookies, changeListeners, HAS_DOCUMENT_COOKIE, _updateBrowserValues, and 7 more.ts(2345)
```

**Comment by eXon** [comment]
Doing this does not align with how React hooks work. It is not a breaking change I am willing to make.
