### ISSUE TITLE
Calling setCookie with options does not set sameSite

### ISSUE THREAD

**Issue by torenware** [reactivestack/cookies#289]
I'm getting the error

> Cookie “flash” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

on Firefox.  I'm using useCookies, and have tried to make the problem go away by calling setCookie with an options argument:

```javascript
  const addFlash = (message) => {
    setCookie('flash', message, { sameSite: true });
  };
```

This does not make the FF warning go away.  Curious what exactly was getting generated as the cookie, I took a look at what actually gets generated by looking at window.cookie:

Running this:

```javascript
const addFlash = (message) => {
    setCookie('flash', message, { sameSite: true });
    console.log('raw cookie', document.cookie);
    // But note that calling serialize directly 
    // *does* append the option:
    console.log(cookie.serialize('flash', message, { sameSite: true }));
  };
```
I then see this in my logs when addFlash() runs:

```
 raw cookie flash=Sold%20ticket%20for%20%22Flash%20Gerdin%22
flash=Sold%20ticket%20for%20%22Flash%20Gerdin%22; SameSite=Strict
```

Am I calling setCookie() incorrectly, or is it just (incorrectly?) ignoring my options for the cookie?

**Comment by eXon** [comment]
It should be working fine with the last version. Let me know if it's not.
