### ISSUE TITLE
Remove Cookie not working properly

### ISSUE THREAD

**Issue by krishnaTORQUE** [reactivestack/cookies#290]
```
const [cookies, setCookie, removeCookie] = useCookies();

setCookie('key', value, {
          path: '/',
          maxAge: 86400 * 365,
        });

removeCookie('key');
```

Sometime cookie does not removing

**Comment by theStonedSage** [comment]
hey , were you able to solve the issue ?

**Comment by krishnaTORQUE** [comment]
No, the issue is still there

**Comment by Nahov91** [comment]
I just ran into this issue. For me it seems like adding the path as option in removeCookie fixed it.
So  removeCookie('key', { path: '/' })
It is weird as it is not an issue that happened on all occasions, but only sometimes.

**Comment by krishnaTORQUE** [comment]
> I just ran into this issue. For me it seems like adding the path as option in removeCookie fixed it.
> So removeCookie('key', { path: '/' })
> It is weird as it is not an issue that happened on all occasions, but only sometimes.

Yes you are correct.
Also the solution you provided, looks working for me.

**Comment by rudian** [comment]
> I just ran into this issue. For me it seems like adding the path as option in removeCookie fixed it.
> So removeCookie('key', { path: '/' })
> It is weird as it is not an issue that happened on all occasions, but only sometimes.

it not working for me

**Comment by torresandres** [comment]
@Nahov91 Thanks, your workaround fixed this issue for me too.

**Comment by tankvt** [comment]
I suppose the docs missing the value for the removeCookie function. You can remove the cookie like this 
```
removeCookie('key', '')
```

The options **{ path: '/' }**  just write the new value for the cookie as **%7B%22path%22%3A%22%2F%22%7D**

Hope this help

**Comment by eXon** [comment]
You have to specify the path for removing as well. It would solve your issue.

**Comment by lhguerra** [comment]
Cant the path '/' be default? I'm not setting a path when creating the cookie, so it feels very weird to have to tell it when removing.
