### ISSUE TITLE
useLayoutEffect is causing warnings in SSR

### ISSUE THREAD

**Issue by snelsi** [reactivestack/cookies#295]
Following #288

## Summary

`useLayoutEffect` is causing console warnings when using in SSR

## Background

I'm using `useCookies` hook in a Next.js application. After updating to `4.1.0` I'm getting this error:
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. 
This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. 
To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. 
See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
```

## Possible solution

Swapping `useLayoutEffect` with this custom `useIsomorphicLayoutEffect` might help:
```jsx
const isHopefullyDomEnvironment =
  typeof window !== 'undefined' &&
  typeof window.document !== 'undefined' &&
  typeof window.document.createElement !== 'undefined'

export const useIsomorphicLayoutEffect = isHopefullyDomEnvironment
  ? useLayoutEffect
  : useEffect
```

Check out this PR for more info: https://github.com/reduxjs/react-redux/pull/1444

**Comment by eXon** [comment]
The server-side is now skipping it since the change event does not need to be used on SSR. Released in v4.1.1
