### ISSUE TITLE
Cannot work server-side!

### ISSUE THREAD

**Issue by maxgalbu** [reactivestack/cookies#61]
Hi,

with this code:

```js
var express = require('express');
var router = express.Router();
var reactCookie = require('react-cookie');

router.get('/', function(req, res) {
    reactCookie.plugToRequest(req, res);

    someFuncWithCallback( function() {
        var cookie = reactCookie.load("somecookie");
    });
});
```

If two people request this route at the same time and the callback gets called first for the 1st user, the `cookie` will be the cookie of the second user.

Because you store the `rawCookies` globally in your script, instead of using a different `rawCookies` for each request, the first request will call plugToRequest() that will write `rawCookies`, and the second request will overwrite it... and by the time node.js has reached `cookie.load()`, it will return the second cookie to the first user, or viceversa...

**Comment by prog666** [comment]
I've just got the same problem

**Comment by eXon** [comment]
This is because it is not the way this plugin is intended to work. You must call `plugToRequest` just before `renderToString`. Because this operation is sync, you will not have any problem 

This plugin is not a Node.js plugin but a React.js plugin. You should not use this plugin for strictly server-side code.

**Comment by prog666** [comment]
But i need cookies in my async actions for fetching data from server. I will try to fix this by using `node-continuation-local-storage`

**Comment by prog666** [comment]
no, you probably have to use continuation-local-storage outside of react-cookie. It passes context only in nested functions

**Comment by EdwardNelson** [comment]
@prog666 Did you find a solution to this?

**Comment by prog666** [comment]
@EdwardNelson nope, i pass cookies manually to my fetch requests and use plugToRequest just before renderToString.

**Comment by olmer88** [comment]
@prog666 Currently I use this solutoin: I call plugToRequest two times, one just before I call my async action and one just before I call renderToString(). In my async action I use cookies before I do something async. If for example I need cookie value after I get response from db then I save cookie in some variable before request, so I do not need to fetch it from react-cookie.
There are also a little bit simpler and maybe in your case more reliable approach. If you need some cookie value in your async actions - you can store it redux state, so it will be globally available and not dependent on react-cookie.
This library also has other problems. It designed to be used with exppress and express-coockie middleware. In other case you will have problems with saving cookies.

**Comment by EdwardNelson** [comment]
@prog666 @olmer88 Thanks for the suggestions. I think I will just store the value in redux state

**Comment by eXon** [comment]
@maxgalbu @prog666 @EdwardNelson @olmer88 @staylor react-cookie 2 now supports async server-rendering a lot better

**Comment by prog666** [comment]
great news!

**Comment by edalford11** [comment]
I think it would be very responsible of the maintainer to put in the readme that react-cookie (< 2) should not be used server side. It is very concerning that such a huge security like this is not listed in big letters in the readme.
