### ISSUE TITLE
secure: true doesn't appear to be working

### ISSUE THREAD

**Issue by iamchristopher** [reactivestack/cookies#63]
I'm using this package on a project that needs to be PCI compliant and testing in Chrome. One of the requirements is to use secure cookies, which `react-cookie` provides. Unfortunately this feature doesn't appear to be working correctly right now.

```js
cookie.save('key', 'value', {
    secure: true
});
```

Manually setting the cookie seems to work:

```js
document.cookie = "key = value;secure";
```

I'm using `1.0.4`.

**Comment by iamchristopher** [comment]
Ping @eXon

**Comment by eXon** [comment]
@iamchristopher do you have an example of your code?

When using react-cookie, setting `test` to `value` with `secure: true` is going to do `document.cookie = "test=value; Secure"`

**Comment by eXon** [comment]
@iamchristopher is it still a problem?

**Comment by GalFriD** [comment]
@eXon  yes, still happens. tested on version 2.0.6
I passed  { path: '/', secure: true } as option and the cookie wasn't saved.

**Comment by twentynine12** [comment]
I'm also having this issue using version 2.0.8 of universal-cookie. The cookie is created fine when passing { path: '/' } as Options, but when I have { path: '/', secure: true } the cookie isn't created at all.

`import Cookies from 'universal-cookie'`
//other code...
`const cookies = new Cookies()`
`cookies.set('refreshToken', response.data.refresh_token, {path: '/', secure: true})`

This is a showstopper for me as have to have secure cookies.

Setting { httpOnly: true } also doesn't work, no cookie is created then either.

`cookies.set('refreshToken', response.data.refresh_token, {path: '/', httpOnly: true})`

**Comment by FrancescoCioria** [comment]
I gave a look at the code and it looks like the cookie management is done with the lib `cookie`.

This is what they say about the `secure` options in their readme: https://github.com/jshttp/cookie#secure

Are you passing `secure: true` in an `http` website? if yes => it won't work as Chrome will actually reject them and it's the correct behaviour

See this topic too: https://productforums.google.com/forum/#!topic/chrome/mi_yiDZoCNc

**Comment by eXon** [comment]
If you make sure you are on HTTPS, secure option should work as intended. Let me know if you're still having troubles.
