### ISSUE TITLE
cookie.load('cookiename') always undefined on server

### ISSUE THREAD

**Issue by simran-k** [reactivestack/cookies#64]
1. I have required cookie-parser and included as a middleware.
2. My server code looks like this

```

 match({routes: routes, location: req.originalUrl }, (error, redirectLocation, renderProps) => {
    console.log("req headers cookie", req.headers.cookie)
    cookie.setRawCookie(req.headers.cookie);
    cookie.save = res.cookie.bind(res);
    cookie.plugToRequest(req, res)
   console.log("cookie load check", cookie.load('cookiename'))  //alwys gives undefined
})
```

What else should I do to make this work?

**Comment by eXon** [comment]
This is how you should be doing it:

```js
match({routes: routes, location: req.originalUrl }, (error, redirectLocation, renderProps) => {
    var unplug = cookie.plugToRequest(req, res)
    // do server-rendering here
    console.log("cookie load check", cookie.load('cookiename'))
    unplug();
})
```

**Comment by eXon** [comment]
Also make sure the path of your cookie is `/` or you might not be able to see it

**Comment by simran-k** [comment]
Hey, @eXon : Thanks. I did this:

```

var unplug = cookie.plugToRequest(req, res)
      console.log("cookie load check frntend", cookie.load('frontendreact'))  //undefined here

      getReduxPromise(renderProps).then(()=> {
          loadOnServer(renderProps, store).then(() => {
            res.status(200);
            handleRender(req, res,renderProps, store, css);
            console.log("cookie load check frntend 2", cookie.load('frontendreact')) //defined here

            unplug();

            console.log("cookie load check frntend 3", cookie.load('frontendreact')) //defined here

          })
      }, err=>{
        console.log("errror happened in redux promise", err)
      });
```

In function `getReduxPromise`, it is undefined. Why would be that?
Also, What is difference between setRawCookie and plugToRequest? I tried using setRawCookie as well but it does not work.

**Comment by simran-k** [comment]
@eXon : To me it looks like that cookie becomes available once an API call is dispatched or something as before that it remains undefined. Could you guide on this please? I need to check if a cookie exists before firing an API call (i.e fire API if cookie does not exist , That's what I am doing through onAppInit but cookie.load always gives undefined there

**Comment by simran66** [comment]
Hey,Could I have a direction on this please?
 @eXon

**Comment by eXon** [comment]
This is really weird because the function has nothing async. There is no reason your cookie would not be defined right off the bat. I'm wildely using it for SSR and never had a problem like this.

Are you sure you don't have a `cookie.save` somewhere in your code within `getReduxPromise` or `loadOnServer`? Can you also console.log your req.cookie / req.cookies and see if your cookies are really there? Have you used the cookie-parser middleware before?

**Comment by eXon** [comment]
@simran66 @simran-k you probably should switch to react-cookie 2. Async server-rendering is now much better supported :)
