### ISSUE TITLE
Not saving object anymore

### ISSUE THREAD

**Issue by joaohkfaria** [reactivestack/cookies#73]
I updated to the last version (2.0.4), and I'm using universal-cookie.

My previous code was working, but now I can't save any object (strings works fine).

Actually, it saves a object without any keys...

**Comment by joaohkfaria** [comment]
It works if before I save I write: `JSON.stringify(object),`

Why not auto stringfy objects like before?

**Comment by eXon** [comment]
@joaohkfaria an object was supposed to be stringified but the check was wrong. Added unit test + fix. You can update to 2.0.5.
