### ISSUE TITLE
Uncaught TypeError: _reactCookie.Cookies.get is not a function

### ISSUE THREAD

**Issue by wsfuller** [reactivestack/cookies#77]
I'm looking at the provided example over and over and unable to get working.

**Using:**
* React: 15.4.2
* React Cookie: 2.0.6
* React-Router: 4.0.0
* Redux: 5.0.3

**index.jsx**

    import React from 'react';
    ...

    ReactDOM.render(
      <Provider store={store}>
        App />
      </Provider>
    )

**App.jsx**

    import React, { Component } from 'react';
    import { instanceOf } from 'prop-types';
    import { BrowserRouter, Route, Switch, Link, NavLink } from 'react-router-dom';
    import createBrowserHistory from 'history/createBrowserHistory'
    const history = createBrowserHistory();
    import { CookiesProvider, withCookies, Cookies } from 'react-cookie';

    export default class App extends Component{
      static propTypes = {
        cookies: instanceOf(Cookies).isRequired
      };
      componentWillMount() {
        const { cookies } = this.props;
        this.state = {
          name: Cookies.get('name')
        };
      }

      render(){
        return(
          <div>
            <CookiesProvider>
              <BrowserRouter>
                <Layout />
              </BrowserRouter>
            </CookiesProvider>
            {this.props.children}
          </div>
        );
      }
    }

I've made a cookie in Chrome `document.cookie="name=John;"`

**Errors:**
* `bundle.js?ce98538…:9753 Warning: Failed prop type: The prop `cookies` is marked as required in `App`, but its value is `undefined`.
    in App`
* `Uncaught TypeError: _reactCookie.Cookies.get is not a function`

The goal is to get a cookie and render my React app off a couple values stored. However unable to get this plugin to even get a cookie.

**Comment by eXon** [comment]
There is two problems with your example. First, you are trying to get the cookies on a component outside the `<CookiesProvider />`. If you move it outside the App on the render call, you would be able to use it within App. Otherwise, you can only use it within your Layout / anything else within components.

You also forgot about the withCookies. It is a high HOC (high order component) that will give you access to the cookies prop.

Keep in mind that if you don't need to access the cookies directly on the App component, you can keep it there and use the withCookies on other components.

Take a look at the example on the readme and I'm sure you'll figure it out.

This should work:

**index.jsx**

```js
import React from 'react';
import { CookiesProvider } from 'react-cookie';
...

ReactDOM.render(
  <Provider store={store}>
    <CookiesProvider>
      <App />
    </CookiesProvider>
  </Provider>
)
```

**App.jsx**

```js
import React, { Component } from 'react';
import { instanceOf } from 'prop-types';
import { BrowserRouter, Route, Switch, Link, NavLink } from 'react-router-dom';
import createBrowserHistory from 'history/createBrowserHistory'
const history = createBrowserHistory();
import { withCookies, Cookies } from 'react-cookie';

class App extends Component{
  static propTypes = {
    cookies: instanceOf(Cookies).isRequired
  };
  componentWillMount() {
    const { cookies } = this.props;
    this.state = {
      name: Cookies.get('name')
    };
  }

  render(){
    return(
      <div>
        <BrowserRouter>
          <Layout />
        </BrowserRouter>
        {this.props.children}
      </div>
    );
  }
}

export default withCookies(App);
```

**Comment by wsfuller** [comment]
Awesome thank you so much for the help was able to get it to work! 

Especially appreciate you giving such a detailed response, going to read up on High Order Components now to get a better understanding of what is happening. First from scratch React app so plenty to still learn. 

Again thanks for the help and making a great tool.

**Comment by eXon** [comment]
@wsfuller My pleasure.  We were all beginners first so I'm keeping that in mind =)
