### ISSUE TITLE
Getting name of cookies with names that varies?

### ISSUE THREAD

**Issue by alfreden** [reactivestack/cookies#78]
I'm trying to use cookies to store items for a shopping cart and I am almost finished with the code but I am missing out a small part.

I had planned to use `cookies.getAll()` method to catch all the cookies and render them in the shopping cart. However, the `getAll()` method stores all the objects inside of a object. And if i want to get an item out of the object i have to write `cookies.getAll()."InsertNameOfCookie".ID` is there a smart way to get ahold of NameOfCookie and render it? 
A console.log of getAll will then show the following if I have multiple cookies. The names will change alot.
`object{Bike: object, Pizza: object, SkateBoard: object }`

I am storing the cookies like this. 
```
    addProduct(){
        const { cookies } = this.props;

        cookies.set(this.state.itemList.name, this.state.itemList, { path: '/' });
    }

    componentWillMount(){
        var itemList = this.props.location.state;
        this.setState({itemList});

        const { cookies } = this.props;

        this.state = {
            [this.state.itemList.name]: cookies.get(this.state.itemList.name)
        };

    }
```

I have looked around alot  for ways to do this. But, no luck so far. Anyone here got any ideas on how to do this? I would really appreciate if anyone have any input at all on this.

**Comment by eXon** [comment]
You can use Object.keys(allCookies) to get every cookie names. Afterward you can filter and display them
