### ISSUE TITLE
why v2 change so much  compared to v1

### ISSUE THREAD

**Issue by tiemei** [reactivestack/cookies#79]
Last year, I use v1.4，but I found react-cookie change to v2, why ? How I choose?

**Comment by eXon** [comment]
It depends on your needs. The v2 is designed for better server-rendering / async support so if you are doing it you should definitively upgrade. If you want to keep using a simple API only on the client, you can use tje universal-cookie package.

**Comment by spsneo** [comment]
I have been using react-cookie 1.4 for sometime.
I have used it also in redux actions. Now in v2 I see that it has become a HOC. Is there a way I can continue to use react-cookie v2 without removing its usage in redux actions?

**Comment by eXon** [comment]
@spsneo If you are using redux, I recommend that you use directly `universal-cookie` and you would be able to do `cookie.get` and `cookie.set` directly within your action creators.

If you are doing server-rendering, just make sure to include the cookie instance within your action creators parameter. That way you are async-proof (see the doc of universal-cookie for that).

**Comment by akash-okutech** [comment]
@eXon Did not understand the last line of being async-proof ? Can you explain as i am planning for server-rendering ?

**Comment by spsneo** [comment]
@eXon  Thanks for your quick response. I have just one more doubt. I am using cookie in react component as well as redux action creators. How do you recommend to instantiate cookie so that it works well on both client as well as server. In server I don't have req context in `renderToString`

**Comment by eXon** [comment]
@akash-okutech In react-cookie 1, all the cookies were saved in the same store. That means when you are doing anything in parallel, your cookies will end up overlapping because they can't know in which request they stand.

In react-cookie 2, you have a Cookie instance and using react-cookie you can access it anywhere within your code. Now, even if you have two request at the same time, you can be sure nobody is going to end up  with the cookies of other users because it is no longer a global state. I've seen it in my own production apps and it's not fun to have server-rendering show admin accesses to a regular user.

If you don't care about server-rendering, you can use universal-cookie and you'll be fine. But I suggest that you try react-cookie if you are planning to do server-rendering latter.

**Comment by eXon** [comment]
@spsneo 

You can use react-cookie with Redux pretty easily. You just need to dispatch an action that will dispatch the cookie instance and the reducers using it can save it for latter usage.

Something like this:

```js
dispatch({
  type: 'COOKIE_INIT',
  payload: this.props.cookies
})
```

The only concern I have however is you can't rehydrate the cookies instance. Just make sure the client-side re-init it.

I'll try to write an example when I have sometime. I think a lot of people are going to find it helpful.

**Comment by eXon** [comment]
@spsneo For the action creators, you can give `this.props.cookies` in parameter and you'll be able to use it as you like.

**Comment by eXon** [comment]
@spsneo For the server-side, you'll need to have access to at least the `cookie` header. If you have it, you can simply do: `new Cookies(cookieHeader)` and pass it to your app all the way to your `<CookiesProvider />`.

**Comment by spsneo** [comment]
@eXon Thanks for explaining. I am almost there. Only point where I am now stuck is `react-router`. I am using v3. In server side rendering I use their [`match`](https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#match-routes-location-history-options--cb) api. Also I am wrapping my router component with `withCookies`. So I am not sure how do I pass `CookiesProvider` in `match` api of react-router.

**Comment by eXon** [comment]
@spsneo The key for server-rendering is to create your `Cookies` instance as soon as possible within your request. You don't need the `CookiesProvider` until you are doing the `renderToString` and at that point, you just pass it as a prop to your `<App />` component.

I'm guessing you are using static methods on your components to fetch data. You can pass the `Cookies` instance there and use the same on your `<CookiesProvider />`. 

It works the same way the Redux store works. You just give it to your app container and it takes care of giving it back to the provider.

**Comment by spsneo** [comment]
@eXon `match` api of react-router uses <Router> component and <Router> component is wrapped with `withCookies`. And I am assuming `withCookies` requires `<CookiesProvider />` . Here's a sample code:
`
app.get('*', (req, res) => {
  console.log(req.headers);
  const cookies = new Cookies(req.headers.cookie || '');
  match({routes: Routes(), location: req.url}, (err, redirectLocation, renderProps) => {
    if (err) {
      let errorHtml = <div>Invalid Route.</div>;
      res.status(500).send(errorHtml);
      return;
    };

    if (redirectLocation) {
      res.redirect(302, redirectLocation.pathname + redirectLocation.search);
      return;
    }
      
    const body = renderToString(
      <CookiesProvider cookies={cookies}>
        <Provider store={store}>
          <RouterContext {...renderProps} />
        </Provider>
      </CookiesProvider>
    );

    res.render('index', {body, state: store});
  });
});
`

**Comment by spsneo** [comment]
@eXon And I get this error
```
TypeError: Cannot read property 'cookies' of undefined
    at Wrapper
```

**Comment by eXon** [comment]
@spsneo doesn't look like the problem is within that file. Would you mind sharing your Wrapper?

**Comment by davincho** [comment]
@eXon I am not sure if dispatching the cookie instance is the best way. Can't remember where, but I think I read once that one should only dispatch 'plain' objects/data.

I had the same problem when trying to access cookies within my actions. As I am using redux-thunk as a middleware, one can provide an additional third argument (https://github.com/gaearon/redux-thunk#injecting-a-custom-argument).
On the server I have access to the cookie instance via `req.universalCookies`, on the client I just create a new cookie instance (same behaviour as https://github.com/reactivestack/cookies/blob/master/packages/react-cookie/src/CookiesProvider.js#L18) like so:

```javascript
thunk.withExtraArgument({
  api,
  // On client we create new cookies instance
  cookies: cookies || new Cookies()
})
```

I any action you have access to your cookie instance via the third parameter:

```javascript
export function reAuthenticate() {
  return (dispatch, getState, { cookies }) => {
    const token = cookies.get(COOKIE_NAME);
  };
}
```
If you don't use `redux-thunk` you can easily write your own middleware providing access to the cookie instance in any redux action.

**Comment by spsneo** [comment]
@davincho Thanks for detailed explanation. Helps a lot.

**Comment by gilles-yvetot** [comment]
@davincho thanks for the explanation ! I just wanted to be sure:

`new Cookies()` came from `import { Cookies } from 'react-cookie';` right ?

But where does `cookies` when you init your thunk with the extra parameter?

**Comment by davincho** [comment]
@gilles-yvetot my `server.js` looks like that:

```javascript

import cookiesMiddleware from 'universal-cookie-express';

const server = express();

server.use(cookiesMiddleware()).use((req, res) => {
  const store = createStore({
    serverCookies: req.universalCookies
    // other params
  });
});


```

and creating the redux store looks like this:

```javascript

import Cookies from 'universal-cookie';

export default ({
  serverCookies
  // other params
}) => {
  const cookies = serverCookies || new Cookies();
  const reduxMiddleware = [
    thunk.withExtraArgument({
      api,
      cookies
    })
  ];
  // create redux store and return it
};


```

In `client.js` I don't pass any serverCookies, so `cookies` defaults to `new Cookies()`.

**Comment by gilles-yvetot** [comment]
Oh I see now ! Thanks a lot !

**Comment by elhachimi** [comment]
Can someone please gives more insight on how to pass `serverCookies` to `thunk` `extraArgument`?
 thanks

**Comment by davincho** [comment]
@elhachimi please have a look at my code sample. extraArgument is just a plain object.

**Comment by elhachimi** [comment]
Yes @davincho but i'me struggling getting the `serverCookies` from `server.js` ,
i don't really understand how you can get the `serverCookies` here
```
export default ({
  serverCookies
  // other params
}) =>
```
and why are you creating a `store` in `server.js`
```
 const store = createStore({
    serverCookies: req.universalCookies
    // other params
  });
````
Thanks a lot for your help

**Comment by davincho** [comment]
Keep in mind, that this code is ES6. You can destructure an object do get only those values you need (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Unpacking_fields_from_objects_passed_as_function_parameter)

`server.js` needs its own store (have a look at http://redux.js.org/docs/recipes/ServerRendering.html#server-rendering)

**Comment by elhachimi** [comment]
👍 thanks @davincho actually made it work by setting two `Provider` with different `stores`

**Comment by sebmor** [comment]
Is there a repo anywhere I can look at with this example?

**Comment by sebmor** [comment]
@davincho any suggestion on how would you go about passing your cookies by default as header in your api calls both server side & client side in your example?
I'm using your solution but I manually add the header to each api request atm.

**Comment by davincho** [comment]
@sebmor Probably a curried function for creating your API?

```javascript

export default (cookies) => ({
  get: (url, params) => {
    // Do something with cookies, url, params
  },
  /** More code **/ 
})

```

```javascript
const cookies = serverCookies || new Cookies();

const reduxMiddleware = [
    thunk.withExtraArgument({
      api(cookies),
      cookies
    })
  ];
```
