### ISSUE TITLE
maxAge handled incorrectly w/ express middleware

### ISSUE THREAD

**Issue by pschlette** [reactivestack/cookies#81]
I believe the `maxAge` is handled incorrectly in the express middleware. I noticed it behaving strangely while integrating universal-cookie into my app and saw this in the source:

https://github.com/reactivestack/cookies/blob/master/packages/universal-cookie-express/src/index.js#L17

`expressOpt.maxAge` is converted to milliseconds, but ultimately `expressOpt` isn't passed to the call to `res.cookie`; the original `options` (with the `maxAge` still in seconds) is.

**Comment by eXon** [comment]
Thanks for the issue. This is fixed in 2.0.6 =)

**Comment by martinhorsky** [comment]
@eXon Can you release `2.0.6` of `universal-cookie-express`? There is still `2.0.5` in the registry. Thanks.

**Comment by eXon** [comment]
@martinhorsky Sorry about the delay. It's published now.
