### ISSUE TITLE
Missing the cookie header or object

### ISSUE THREAD

**Issue by davidsonsns** [reactivestack/cookies#84]
I am using `universal-cookie` and am experiencing this problem when instantiating it. I'm doing the same thing as the example:

```
import Cookies from 'universal-cookie';
const cookies = new Cookies();
```

**Comment by garythung** [comment]
Running into this issue as well. `universal-cookie` seems to think I'm using this on the server side but it's on client side.

**Comment by davidsonsns** [comment]
I returned to the version I was using the longest, `"react-cookie": "^ 0.4.8"`

**Comment by eXon** [comment]
With what bundler are you using this library? It seems like it is mistakingly thinking you are in a Node.js environment.

**Comment by garythung** [comment]
I'm using Webpack with React and universal routing, which I think is the problem.

**Comment by eXon** [comment]
If you care about async server-rendering you should definitively use `react-cookie` instead. However, `universal-cookie` should be working on Webpack. I'll take a look.

**Comment by Brantron** [comment]
Currently having this issue when running tests as well.

**Comment by eXon** [comment]
@Brantron when testing, you might want to mock your cookies and passing it to the `Cookies` constructor. But yea I kinda agree it should not block you from not donig so in Node.js. I'm trying to look if removing this check has an impact on other parts.

**Comment by eXon** [comment]
@garythung @davidsonsns I've fixed this issue in v2.0.8. Can you confirm you no longer have this issue?

**Comment by andrefox333** [comment]
Using 2.0.8 and getting error: Error: Missing the cookie header or object.

Using universal-cookie with server side rendering and hot reload. I would comment out the code, refresh the page and it loads the page. I'll then uncomment the new Cookie() code and reload the page and it fully works after that...

**Comment by eXon** [comment]
@andrefox333 this is because you are doing server-rendering but you are not providing the cookie header or object to the library. Thus, the cookies will be empty even if the user have some. You need to provide them in some way using `universal-cookie-express` and `react-cookie` or using your own custom way.

Would you mind sharing your code or the portion dealing with cookies and SSR?

**Comment by garythung** [comment]
@eXon I appreciate the work you've put in. Unfortunately, I've moved from universal rendering to just client side, so the `universal-cookie` is working great for me.

**Comment by kunokdev** [comment]
Guys I came across this issue when using Next.js for server side rendering.
My solution was:
Instead of initializing object from class in global scope, I moved it to `componentDidMount` and this error was gone, hope it helps!

**Comment by tamal-appsbee** [comment]
Still facing the same issue. Any solution ?

**Comment by kunokdev** [comment]
@tamal-appsbee are you server side rendering? can u show your code where u get error?

**Comment by tamal-appsbee** [comment]
@kunokdev thanks for reply.
Yes I am using server side rendering.
I have a file name : cookie.js has following content
```
import Cookies from 'universal-cookie';
export const cookies = new Cookies();
```

**Comment by kunokdev** [comment]
you are getting error at this line; `export const cookies = new Cookies();`
Since you are server side rendering, constructor of Cookies class gets broken because it excepts browser environment. Basically you need to make sure you call this constructor when it reaches client side. One way to do that is to put that logic inside `componentDidMount`, see comment above.

**Comment by tamal-appsbee** [comment]
Ok,
Otherwise I shall use 
`
const cookies = new Cookies(req.headers.cookie);
`

this way ?

**Comment by kunokdev** [comment]
I haven't used this approach, to me it seems it would be used inside routers where `req` is available. As for React Components you should use cookie middle-ware to merge these scopes. I haven't succeed at that.

**Comment by kunokdev** [comment]
This is my method for getting list of users:
```
// @input: auth object
// @output: array of users
module.exports.fetch = function(auth){
  return new Promise((resolve, reject)=>{
    let params = {
        auth,
        customer: 'my_customer',
        maxResults: 100
    }
    directory.users.list(params, (err, res)=>{
      err ? reject(err)
          : resolve(res.users)
    })
  })
}
```
and this is how I use it with auth method from above:

```
const auth = require('../modules/auth.js')
const users = require('../modules/users.js')

auth.jwt('myname@mydomain.com')
.then(users.fetch)
```
Can you check if you are giving it proper params? User email I give it is email of admin user.

**Comment by tamal-appsbee** [comment]
ok, Thanks

**Comment by Brantron** [comment]
Just to loop back, our solution was to just stub this object.

**Comment by andrefox333** [comment]
@Brantron can you provide a code example of what you described above?

**Comment by Brantron** [comment]
Sorry! That would certainly have been helpful. We wrapped our cookie usage in a helper object and just stubbed access like

```
sinon.stub(CookieHelpers, 'getUserStatus').returns({
    signedIn: true,
    mentor: true
  });
`

**Comment by mmoustai** [comment]
@eXon Why did this issue was closed ? I am doing server side rendering and I would like to know if it's possible to get instance of the cookie object outside a component. I am getting the same errors as @andrefox333.

I have a single util function and I want to know if I need to give the cookie from the component as a new argument at every call or I might be able to access it as a "global".

**Comment by eXon** [comment]
@mmoustai You must pass the Cookies object as an argument. You cannot use a global variable otherwise you risk hijacking the cookies from another user.

**Comment by mshavandi** [comment]
still having this issue. `cookies.get()` works as long as I haven't reloaded the page after setting cookie, but when I reload the page, it returns: `undedined`

**Comment by eXon** [comment]
@mshavandi Do you have a step by step or repo to reproduce the issue?
