### ISSUE TITLE
Failed context type: The context `cookies` is marked as required in `withCookies(App)`, but its value is `undefined`.

### ISSUE THREAD

**Issue by balciseri** [reactivestack/cookies#86]
I'm following the Simple example but it doesn't set the cookies prop.
```
import React, { Component } from 'react';
import { CookiesProvider, withCookies, Cookies } from 'react-cookie';

class App extends Component {
  render() {
    return (
      <CookiesProvider>
        <div>
          <strong>props: {JSON.stringify(this.props)}</strong>
          <br />
          <strong>cookizor: {JSON.stringify(new Cookies().getAll())}</strong>
          <br />
          <strong>cookizor2: {JSON.stringify(this.props.cookies)}</strong>
        </div>
      </CookiesProvider>
    );
  }
}
export default withCookies(App);
```
Results in:
```
props: {}
cookizor: {"i18next":"en"}
cookizor2:
```
What am I doing wrong?
Edit: After more tests and with a console.log(this.props) in the render method i can see that cookies is added to this props, but it's value is undefined.
Edit: If you need more infos or if this isn't supposed to be here let me know

**Comment by balciseri** [comment]
I've found the solution.

The example is wrong.

You say to: 
```
class App extends Component {
...
return (
      <CookiesProvider>
...
      </CookiesProvider>
    );
 }
then
export default withCookies(App);
```
well i have little knowledge of providers, context manipulation and such but after spending some time reading about it... I now see why that could never work.

Solution:
```
class App extends Component {
  render() {
    return (
      <CookiesProvider>
          <WithCookiesComponent />
      </CookiesProvider>
    );
  }
}
export default App;

const MyComponent = (props) => (
  <div>{props.cookies.get('i18next')}</div>
);

const WithCookiesComponent = withCookies(MyComponent);
```
Now it works. So i guess you cant supply to withCookies() the Component that is the father of <CookiesProvider> but you have to provide the child component of <CookiesProvider> to withCookies().

Correct?

**Comment by rzmz** [comment]
Got it working thanks to @balciseri 
The example is wrong on this one.

**Comment by eXon** [comment]
Example has been fixed. Thanks for reporting!

**Comment by sajadghawami** [comment]
there is still this line missing:

```
import { CookiesProvider } from 'react-cookie';
```
