### ISSUE TITLE
What is the difference between universal-cookie and universal-cookie-express?

### ISSUE THREAD

**Issue by shri3k** [reactivestack/cookies#87]
It seems like both point to same code-base. Is there something that I'm missing?

**Comment by balciseri** [comment]
It's probably a typo in the links.
https://github.com/reactivestack/cookies/tree/master/packages/universal-cookie-express
https://github.com/reactivestack/cookies/tree/master/packages/universal-cookie

**Comment by shri3k** [comment]
@balciseri it appears so.

**Comment by eXon** [comment]
Should be fixed. Thanks for pointing this out.
