### ISSUE TITLE
Is react-cookie working well in multi-node environment?

### ISSUE THREAD

**Issue by OscarYuen** [reactivestack/cookies#90]
I am currently using jwt as authentication and server-side rendering react web application.
Since some react component has some graphql query requiring retrieving some user information like email , if I directly input the link which is containing those components, the way is to get the email is from localStorage. However, server-rendering has no localStorage defined and therefore the graphql query would throw error after the component has been mounted.

It could be solved by react-cookie which could replace the function of localStorage. But if I deploy nodejs application to multiple nodes, is it possible for react-cookie to work well in multiple node environment without using ip-hash load balancing ?

**Comment by eXon** [comment]
Yes it is. `react-cookie` is the perfect solution for this because the cookies are automatically sent on every request by the browser. You should have no problem with load-balancers if your app share the same credentials for your users.
