### ISSUE TITLE
Can I use it with React Redux?

### ISSUE THREAD

**Issue by chandan7193** [reactivestack/cookies#91]
My index.js looks like this
`import React from 'react';
import ReactDOM from 'react-dom';
import {Provider} from 'react-redux';
import {store} from './redux/store';
import Routes from './Routes';
import './index.css';

ReactDOM.render(
	(<Provider store={store}>
  		<Routes />
  </Provider>),
  document.getElementById('root')
);
`
How can I work with it?

**Comment by eXon** [comment]
Yes you can. However, you cannot access the cookies globally now so you will need to dispatch actions with the informations you need. There is a discussion on https://github.com/reactivestack/cookies/issues/79 about how you can accomplish this.

You plug it the same as with React and you dispatch the cookie values that your reducers need basically.
