### ISSUE TITLE
Raw cookie - Using pipes in cookie

### ISSUE THREAD

**Issue by oskarleonard** [reactivestack/cookies#98]
How can i use this lib to write a raw cookie. 

For example 
```
let cookieValue = '0|||57||hi||test||||';
this.props.cookies.set(COOKIE_NAME, decodeURIComponent(cookieValue), {path: '/'});
```
This will create a cookie that encodes the pipes to %7C

While using `document.cookie =`, i can have those pipes inside the cookie:
```
writeRawCookie(COOKIE_NAME, decodeURIComponent(cookieValue), null, '/');
export const writeRawCookie = (name, value, expire, path) => {
    if (areCookiesAvailable()) {
        document.cookie = name + '=' + value + (expire ? ';expires='+expire : '') +';path=' + path;
    }
};
```

**Comment by eXon** [comment]
The pipe character should not be a problem when saving the value. Do you have a particular use-case where the value is not saved correctly?

**Comment by wayweary** [comment]
The problem is that it saves it as %7C instead of |. I think this is bc of how the cookie npm package work (the one used in universal cookie which this package depends on). 
Just try saving a pipe and view in the chrome dev tools how that cookie looks like. 
https://codesandbox.io/s/3v6npnypq1

**Comment by kamil212** [comment]
Same issue here. 
Any luck finding a solution?

**Comment by wayweary** [comment]
Just use the regular way of doing it without this lib, see `writeRawCookie` in my first post.

**Comment by richardklotz** [comment]
just pass an encode function in the options:

 cookies.set('SomeCookie', cookieValue, {
        path: '/',
        encode: value => {     
          //this will return the raw value     
          return value;
        }
      });

**Comment by eXon** [comment]
This will be leaved as is because at this point I don't want to do a breaking change and there is plenty of workaround when necessary.
